"""
Build a mintage lookup from catalog exports sitting in training/.

Mintage figures are published facts (U.S. Mint production records) - the numbers
themselves aren't copyrightable, and they let rare_flags.py derive key-date
rarity systematically instead of leaning on a hand-curated list. Only the FACTS
(series / year / mint / mintage) are read here; catalog images are not fetched
or redistributed.

Rarity is scored as a percentile *within each series*, because absolute mintage
is meaningless across denominations (Morgan median ~5,000,000 vs Braided Hair
Half Cent median ~100).

To widen coverage: export another table from the catalog into training/ as
"<anything>Export<anything>.json" and re-run this script.

Output: mintage_data.py (committed - small, derived facts).
"""
import glob
import json

OUT_PATH = "mintage_data.py"

# Catalog spells mints out; inventory rows carry the mintmark letter.
MINT_MARKS = {
    "philadelphia": "P",
    "san francisco": "S",
    "new orleans": "O",
    "denver": "D",
    "carson city": "CC",
    "west point": "W",
}


def load_rows():
    rows = []
    paths = sorted(glob.glob("training/*Export*.json"))
    if not paths:
        print("No training/*Export*.json files found.")
    for path in paths:
        with open(path) as f:
            data = json.load(f)
        groups = list(data.values()) if isinstance(data, dict) else [data]
        n = 0
        for group in groups:
            for r in group:
                mint = MINT_MARKS.get(str(r.get("Mint", "")).strip().lower())
                series, year = r.get("Series"), r.get("Year")
                try:
                    mintage = int(r.get("Mintage"))
                except (TypeError, ValueError):
                    continue
                if not (mint and series and year) or mintage <= 0:
                    continue
                rows.append((str(series), int(year), mint, mintage))
                n += 1
        print(f"  {path}: {n} usable rows")
    return rows


def build():
    rows = load_rows()
    if not rows:
        return

    # rank within series: 1 = lowest mintage (rarest)
    by_series = {}
    for series, year, mint, mintage in rows:
        by_series.setdefault(series, []).append((mintage, year, mint))

    table = {}
    for series, entries in by_series.items():
        entries.sort()  # ascending mintage
        size = len(entries)
        for rank, (mintage, year, mint) in enumerate(entries, start=1):
            table[(series, year, mint)] = (mintage, rank, size)

    with open(OUT_PATH, "w") as f:
        f.write('"""\n')
        f.write("AUTO-GENERATED by build_mintage_table.py - do not edit by hand.\n\n")
        f.write("Published U.S. Mint production figures, keyed by (series, year, mintmark).\n")
        f.write("Value is (mintage, rank_within_series, series_size); rank 1 = lowest\n")
        f.write("mintage in that series, i.e. the rarest date/mint of that type.\n")
        f.write('"""\n\n')
        f.write("MINTAGE = {\n")
        for key in sorted(table, key=lambda k: (k[0], k[1], k[2])):
            series, year, mint = key
            mintage, rank, size = table[key]
            f.write(f'    ("{series}", {year}, "{mint}"): ({mintage}, {rank}, {size}),\n')
        f.write("}\n")

    print(f"\nWrote {len(table)} entries to {OUT_PATH}")
    for series, entries in sorted(by_series.items()):
        lo = min(e[0] for e in entries)
        print(f"  {series:<26} {len(entries):>3} dates   rarest mintage {lo:,}")


if __name__ == "__main__":
    build()
