# Coin/set inventory data, compiled by visual identification of the photos in
# coin_images/. Each row is one item (a single coin, or a full set/token where
# the pieces aren't sold apart). Values are rough reference-guide ranges for
# common circulated/typical-grade examples in original packaging where noted -
# actual grade-sensitive value requires an in-hand look or a certified grade.
#
# confidence: "high" = design/date clearly legible; "medium" = design certain,
# date probable; "low" = read from a rotated/worn/glare-affected coin, verify
# in hand.

INVENTORY = [
    # ---------------- MINT / PROOF SETS ----------------
    {
        "photo_group": "Set 1", "source_images": "IMG_1198, IMG_1199",
        "category": "Proof Set", "denomination": "Cent/Nickel/Dime/Quarter/Half Dollar (5 coins)",
        "country": "USA", "year": 1960, "mint_mark": "(none - Philadelphia, pre-1968 proofs unmarked)",
        "design_variety": "1960 U.S. Proof Set in original hard-plastic holder",
        "coin_spec_key": None,
        "obverse_text": "Individual coins: LIBERTY / IN GOD WE TRUST + date on each",
        "reverse_text": "Holder engraved: \"U.S. PROOF COINS 1960\"",
        "condition_notes": "Sealed in period Capital-style plastic holder, light haze/toning visible on cent and nickel, dime/quarter/half show cameo-like mirror fields",
        "qty": 1,
        "est_value_low_usd": 32, "est_value_high_usd": 50,
        "value_basis": "Greysheet/USA Coin Book 2026 guide, large-date vs small-date cent variety affects low/high end",
        "confidence": "high",
        "notes": "Cent/nickel are base metal; dime, quarter, half are 90% silver. Large-date vs small-date cent variety changes value - check cent closely.",
    },
    {
        "photo_group": "Set 2", "source_images": "IMG_1214",
        "category": "Mint Set", "denomination": "Cent/Nickel/Dime/Quarter/Half Dollar",
        "country": "USA", "year": 1974, "mint_mark": "P (Philadelphia panel photographed)",
        "design_variety": "1974 U.S. Mint Uncirculated Set, sealed cellophane pack",
        "coin_spec_key": None,
        "obverse_text": "Kennedy half visible: LIBERTY / IN GOD WE TRUST 1974",
        "reverse_text": "n/a (sealed pack)",
        "condition_notes": "Still factory-sealed in original cellophane with red stripe",
        "qty": 1,
        "est_value_low_usd": 15, "est_value_high_usd": 19,
        "value_basis": "Greysheet ($15) / USA Coin Book (~$19) 2026 guide for complete P&D set",
        "confidence": "high",
        "notes": "Only the Philadelphia panel was photographed - full 1974 Mint Set includes a matching Denver (D) panel; check the envelope for a second sealed panel before assuming this is complete.",
    },
    {
        "photo_group": "Set 3", "source_images": "IMG_1215",
        "category": "Mint Set", "denomination": "Cent/Nickel/Dime/Quarter/Half Dollar/SBA Dollar",
        "country": "USA", "year": 1998, "mint_mark": "P&D",
        "design_variety": "1998 U.S. Mint Uncirculated Set, sealed cellophane pack",
        "coin_spec_key": None,
        "obverse_text": "Susan B. Anthony Dollar (LIBERTY, 1998), Washington quarter, Kennedy half, Roosevelt dime, Jefferson nickel, Lincoln cent all visible",
        "reverse_text": "n/a (sealed pack)",
        "condition_notes": "Factory-sealed cellophane",
        "qty": 1,
        "est_value_low_usd": 5, "est_value_high_usd": 7,
        "value_basis": "Greysheet (~$5.50) / USA Coin Book (~$7.20) 2026 guide",
        "confidence": "high",
        "notes": "1998 was the last year of the Susan B. Anthony dollar before the Sacagawea dollar replaced it in 2000 - a small draw for type collectors.",
    },
    {
        "photo_group": "Set 4", "source_images": "IMG_1216",
        "category": "Mint Set", "denomination": "Cent/Nickel/Dime/Quarter/Half Dollar",
        "country": "USA", "year": 1999, "mint_mark": "P&D",
        "design_variety": "1999 U.S. Mint Uncirculated Set (Delaware state quarter visible), sealed cellophane pack",
        "coin_spec_key": None,
        "obverse_text": "Delaware statehood quarter, Kennedy half, Jefferson nickel, Lincoln cent visible",
        "reverse_text": "n/a (sealed pack)",
        "condition_notes": "Factory-sealed cellophane",
        "qty": 1,
        "est_value_low_usd": 8, "est_value_high_usd": 12,
        "value_basis": "General guide range for early 50-States-era mint sets (first year of state quarter program)",
        "confidence": "medium",
        "notes": "First year of the 50 State Quarters program - modestly more collector interest than later years.",
    },
    {
        "photo_group": "Set 5", "source_images": "IMG_1217",
        "category": "Commemorative Display Card", "denomination": "Nickel (+ cent visible)",
        "country": "USA", "year": 2004, "mint_mark": "P (Philadelphia)",
        "design_variety": "\"Westward Journey\" Keelboat Jefferson Nickel on a themed collector card",
        "coin_spec_key": "Jefferson Nickel",
        "obverse_text": "UNITED STATES OF AMERICA, LEWIS & CLARK, KEELBOAT, FIVE CENTS",
        "reverse_text": "Card text: \"The Westward Journey / Keelboat\", \"Philadelphia Denver 2004\"",
        "condition_notes": "Uncirculated-looking nickel mounted in card, cent below only partly visible",
        "qty": 1,
        "est_value_low_usd": 1, "est_value_high_usd": 3,
        "value_basis": "Common date/mintmark Keelboat nickel is worth face to ~$1 even in high uncirculated grade; card adds small novelty premium",
        "confidence": "high",
        "notes": "Not a full mint set - just the nickel (and a cent) on a promotional display card. No real numismatic premium over face value.",
    },

    # ---------------- TOKENS / EXONUMIA (not U.S. legal tender) ----------------
    {
        "photo_group": "Token 1", "source_images": "IMG_1200",
        "category": "Casino Token", "denomination": "$1.00 (redeemable cash value)",
        "country": "USA (Nevada)", "year": None, "mint_mark": None,
        "design_variety": "Aladdin Hotel & Casino (Las Vegas) \"World's 7 Wonders\" series - Eiffel Tower",
        "coin_spec_key": "Casino Token (base metal)",
        "obverse_text": "ONE DOLLAR REDEEMABLE CASH VALUE / EIFFEL TOWER / ALADDIN",
        "reverse_text": "Aladdin and magic carpet over the casino name (not photographed in this set of images)",
        "condition_notes": "Brass-toned token in a plastic capsule, light wear",
        "qty": 1,
        "est_value_low_usd": 2, "est_value_high_usd": 5,
        "value_basis": "eBay/Worthpoint comparables for individual Aladdin World's 7 Wonders tokens (complete 7-piece $2 sets sell around $18, i.e. ~$2.50/token)",
        "confidence": "high",
        "notes": "Aladdin closed/was demolished in 1998 (site is now Planet Hollywood) - defunct-casino tokens like this have modest but real collector demand.",
    },
    {
        "photo_group": "Token 2", "source_images": "IMG_1201",
        "category": "Casino Token", "denomination": "$2.00 (redeemable cash value)",
        "country": "USA (Nevada)", "year": 1996, "mint_mark": None,
        "design_variety": "Aladdin Hotel & Casino (Las Vegas) \"World's 7 Wonders\" series",
        "coin_spec_key": "Casino Token (base metal)",
        "obverse_text": "TWO DOLLAR REDEEMABLE CASH VALUE / WORLD'S 7 WONDERS / ALADDIN",
        "reverse_text": "Aladdin and magic carpet motif",
        "condition_notes": "Brass-toned token in a plastic capsule, light wear, small edge nick",
        "qty": 1,
        "est_value_low_usd": 2, "est_value_high_usd": 5,
        "value_basis": "Same comparables as Token 1",
        "confidence": "high",
        "notes": "Series issued 1996; there were 7 different wonder designs at $2 each - if there are more of these in the bag, a matched set is worth more together than piecemeal.",
    },
    {
        "photo_group": "Exonumia 1", "source_images": "IMG_1202",
        "category": "Elongated Cent (souvenir)", "denomination": "Rolled 1 cent",
        "country": "USA", "year": 1939, "mint_mark": None,
        "design_variety": "1939 New York World's Fair \"The World of Tomorrow\" - Trylon & Perisphere",
        "coin_spec_key": "Elongated Cent (souvenir)",
        "obverse_text": "NEW YORK WORLD'S FAIR 1939 / THE WORLD OF TOMORROW (rolled over Trylon & Perisphere image)",
        "reverse_text": "n/a (rolled onto a genuine Lincoln cent planchet, original details erased)",
        "condition_notes": "Good detail, brown copper patina, no major creases",
        "qty": 1,
        "est_value_low_usd": 5, "est_value_high_usd": 15,
        "value_basis": "Collector-forum comparables: common 1939 NYWF elongated designs sell for a few dollars, scarcer die varieties up to ~$50; PCGS CoinFacts catalogs this as die variety M&D-1",
        "confidence": "high",
        "notes": "This is a legitimate 87-year-old souvenir elongated coin, not a modern reproduction - collectible in the elongated-coin (\"pressed penny\") hobby, which is a real and organized sub-collecting niche.",
    },

    # ---------------- LOOSE QUARTERS ----------------
    {
        "photo_group": "Quarter 1", "source_images": "IMG_1203, IMG_1205, IMG_1206, IMG_1207, IMG_1213",
        "category": "Circulating Quarter", "denomination": "25 cents",
        "country": "USA", "year": 2006, "mint_mark": "not legible in photo",
        "design_variety": "50 State Quarters - Colorado (\"COLORADO 1876\", Rocky Mountains design)",
        "coin_spec_key": "Washington/State/ATB Quarter (clad, 1965-present)",
        "obverse_text": "UNITED STATES OF AMERICA / LIBERTY / IN GOD WE TRUST",
        "reverse_text": "COLORADO 1876 / mountain landscape",
        "condition_notes": "Circulated, moderate wear",
        "qty": 1,
        "est_value_low_usd": 0.25, "est_value_high_usd": 1,
        "value_basis": "Face value; common-date circulated state quarters carry no premium",
        "confidence": "high", "notes": "",
    },
    {
        "photo_group": "Quarter 2", "source_images": "IMG_1203, IMG_1205, IMG_1207, IMG_1213",
        "category": "Circulating Quarter", "denomination": "25 cents",
        "country": "USA", "year": 2005, "mint_mark": "not legible in photo",
        "design_variety": "50 State Quarters - West Virginia (\"WEST VIRGINIA 1863\", New River Gorge Bridge)",
        "coin_spec_key": "Washington/State/ATB Quarter (clad, 1965-present)",
        "obverse_text": "UNITED STATES OF AMERICA / LIBERTY / IN GOD WE TRUST",
        "reverse_text": "WEST VIRGINIA 1863 / New River Gorge Bridge",
        "condition_notes": "Circulated, light-moderate wear",
        "qty": 1,
        "est_value_low_usd": 0.25, "est_value_high_usd": 1,
        "value_basis": "Face value; common-date circulated state quarters carry no premium",
        "confidence": "high", "notes": "",
    },
    {
        "photo_group": "Quarter 3", "source_images": "IMG_1203, IMG_1205, IMG_1207, IMG_1213",
        "category": "Circulating Quarter", "denomination": "25 cents",
        "country": "USA", "year": 2021, "mint_mark": "not legible in photo",
        "design_variety": "America the Beautiful - Washington Crossing the Delaware (George Washington crossing the Delaware River, boat scene)",
        "coin_spec_key": "Washington/State/ATB Quarter (clad, 1965-present)",
        "obverse_text": "UNITED STATES OF AMERICA / E PLURIBUS UNUM / crossing scene / QUARTER DOLLAR",
        "reverse_text": "(design is on what's usually the reverse face; Washington portrait is on the other side)",
        "condition_notes": "Circulated, light wear",
        "qty": 1,
        "est_value_low_usd": 0.25, "est_value_high_usd": 1,
        "value_basis": "Face value; common-date circulated ATB quarters carry no premium",
        "confidence": "high", "notes": "",
    },
    {
        "photo_group": "Quarter 4", "source_images": "IMG_1203, IMG_1205, IMG_1206, IMG_1213",
        "category": "Circulating Quarter", "denomination": "25 cents",
        "country": "USA", "year": 2001, "mint_mark": "not legible in photo",
        "design_variety": "50 State Quarters - North Carolina (\"NORTH CAROLINA 1789\", First Flight / Wright Flyer)",
        "coin_spec_key": "Washington/State/ATB Quarter (clad, 1965-present)",
        "obverse_text": "UNITED STATES OF AMERICA / LIBERTY / IN GOD WE TRUST",
        "reverse_text": "NORTH CAROLINA 1789 / FIRST FLIGHT / Wright Flyer biplane",
        "condition_notes": "Circulated, moderate wear",
        "qty": 1,
        "est_value_low_usd": 0.25, "est_value_high_usd": 1,
        "value_basis": "Face value; common-date circulated state quarters carry no premium",
        "confidence": "high", "notes": "",
    },
    {
        "photo_group": "Quarter 5", "source_images": "IMG_1206, IMG_1213",
        "category": "Circulating Quarter", "denomination": "25 cents",
        "country": "USA", "year": 2022, "mint_mark": "not legible in photo",
        "design_variety": "American Women Quarters - Maya Angelou (figure with wings/arms raised, rising sun rays)",
        "coin_spec_key": "Washington/State/ATB Quarter (clad, 1965-present)",
        "obverse_text": "UNITED STATES OF AMERICA / QUARTER DOLLAR / E PLURIBUS UNUM",
        "reverse_text": "MAYA ANGELOU / bird in flight / sunrise rays design",
        "condition_notes": "Lightly circulated, good detail",
        "qty": 1,
        "est_value_low_usd": 0.25, "est_value_high_usd": 1,
        "value_basis": "Face value; first-year 2022 American Women Quarter, common in circulation",
        "confidence": "high", "notes": "",
    },

    # ---------------- LOOSE DIMES ----------------
    {
        "photo_group": "Dimes (13)", "source_images": "IMG_1206, IMG_1210, IMG_1213",
        "category": "Circulating Dime", "denomination": "10 cents",
        "country": "USA", "year": None, "mint_mark": "not legible in photo",
        "design_variety": "Roosevelt Dime, various dates",
        "coin_spec_key": "Roosevelt Dime (clad, 1965-present)",
        "obverse_text": "LIBERTY / IN GOD WE TRUST",
        "reverse_text": "not photographed close enough to read",
        "condition_notes": "Moderate to heavy circulation wear, dates too small/worn to read reliably from photo",
        "qty": 13,
        "est_value_low_usd": 1.30, "est_value_high_usd": 30,
        "value_basis": "Face value ($0.10 each) if clad (1965+); ~$2+ each in silver melt alone if any are 1964-or-earlier (90% silver)",
        "confidence": "low",
        "notes": "IMPORTANT: check every one of these 13 dimes for a date of 1964 or earlier - those are 90% silver (worth several dollars each just for the silver, more so if a nicer grade). Quick tell: silver dimes look duller/warmer and show no copper-colored stripe on the edge; clad dimes show a visible copper line on the edge.",
    },

    # ---------------- LOOSE NICKEL ----------------
    {
        "photo_group": "Nickel 1", "source_images": "IMG_1203, IMG_1205, IMG_1206, IMG_1207",
        "category": "Circulating Nickel", "denomination": "5 cents",
        "country": "USA", "year": None, "mint_mark": "not legible in photo",
        "design_variety": "Jefferson Nickel, heavily worn (date not legible)",
        "coin_spec_key": "Jefferson Nickel",
        "obverse_text": "LIBERTY (partial, worn smooth)",
        "reverse_text": "not clearly photographed",
        "condition_notes": "Heavily worn/smoothed, date illegible in photo",
        "qty": 1,
        "est_value_low_usd": 0.05, "est_value_high_usd": 0.05,
        "value_basis": "Face value - worn common-date Jefferson nickels have no numismatic premium",
        "confidence": "medium", "notes": "",
    },

    # ---------------- LOOSE CENTS (bulk) ----------------
    {
        "photo_group": "Penny Grid A - confident reads", "source_images": "IMG_1209, IMG_1210, IMG_1211",
        "category": "Circulating Cent (individually read)", "denomination": "1 cent",
        "country": "USA", "year": "1958/1968, 1969, 1969, 1970, 1972, 1980, 1981, 1982, 1982, 1982, 1984, 1988, 1989, 1989",
        "mint_mark": "not legible in photo",
        "design_variety": "Lincoln Memorial cents - 14 individual coins read with medium-high confidence out of this grid",
        "coin_spec_key": "Lincoln Cent (Memorial, bronze 1959-1982) / (copper-plated zinc 1982-present)",
        "obverse_text": "LIBERTY / IN GOD WE TRUST + date",
        "reverse_text": "Lincoln Memorial building, ONE CENT, UNITED STATES OF AMERICA",
        "condition_notes": "Grid laid out on a tray, many coins rotated/upside-down in the photo which makes some digits ambiguous",
        "qty": 14,
        "est_value_low_usd": 0.14, "est_value_high_usd": 1.50,
        "value_basis": "Face value for common-date circulated memorial cents; pre-1982 examples are 95% copper (worth slightly more than face in copper melt terms, though melting US cents is illegal)",
        "confidence": "medium",
        "notes": "This is one physical layout of ~40+ cents that appears to have been photographed three times (IMG_1209/1210/1211 match in pattern) - these 14 are the ones legible enough to date confidently across those three photos.",
    },
    {
        "photo_group": "Penny Grid A - illegible remainder", "source_images": "IMG_1209, IMG_1210, IMG_1211",
        "category": "Circulating Cent (bulk, unread)", "denomination": "1 cent",
        "country": "USA", "year": None, "mint_mark": None,
        "design_variety": "Mix of Lincoln wheat cents and Lincoln Memorial cents - remaining coins in the same grid",
        "coin_spec_key": "Lincoln Cent (Wheat, bronze 1909-1942, 1944-1958) / (Memorial, bronze 1959-1982) / (copper-plated zinc 1982-present)",
        "obverse_text": "LIBERTY / IN GOD WE TRUST + date (date not reliably legible from photo)",
        "reverse_text": "mix of wheat-ears (pre-1959) and Lincoln Memorial (1959+) reverses visible",
        "condition_notes": "Coins are rotated/upside down/worn; 4-digit dates could not be read reliably without physical handling",
        "qty": 31,
        "est_value_low_usd": 0.93, "est_value_high_usd": 5,
        "value_basis": "Assume face value for memorial cents, ~$0.05-0.15 typical for common circulated wheat cents (no premium unless a key date - see notes)",
        "confidence": "low",
        "notes": "Worth a 10-minute manual sort: flip every cent over - any with WHEAT EARS on the back (not the Memorial building) is 1909-1958 and worth pulling aside. Then check those specifically for key dates: 1909-S, 1909-S VDB, 1914-D, 1922 (no mintmark/\"plain\"), 1931-S, 1955 doubled-die - those are the ones with real premiums ($20 to thousands); everything else is a few cents to ~$0.25 each.",
    },
    {
        "photo_group": "Penny Piles B/C", "source_images": "IMG_1208, IMG_1212",
        "category": "Circulating Cent (bulk, possible duplicate photos)", "denomination": "1 cent",
        "country": "USA", "year": None, "mint_mark": None,
        "design_variety": "Mix of Lincoln wheat cents and Lincoln Memorial cents, scattered (non-grid) layout",
        "coin_spec_key": "Lincoln Cent (Wheat, bronze 1909-1942, 1944-1958) / (Memorial, bronze 1959-1982) / (copper-plated zinc 1982-present)",
        "obverse_text": "LIBERTY / IN GOD WE TRUST + date",
        "reverse_text": "mix of wheat-ears and Lincoln Memorial reverses",
        "condition_notes": "Scattered pile, several coins with dark/black toning consistent with environmental damage or old copper corrosion",
        "qty": 19,
        "est_value_low_usd": 0.57, "est_value_high_usd": 5,
        "value_basis": "Same basis as Penny Grid A remainder",
        "confidence": "low",
        "notes": "IMG_1208 and IMG_1212 show a similar scattered arrangement with overlapping dates and matching dark/corroded coins in similar positions - these may be TWO PHOTOS OF THE SAME ~19 COINS rather than 38 distinct coins. Treat this qty (19) as a single estimate, not 19+19=38, until physically recounted.",
    },

    # ---------------- BATCH 2 (IMG_1233-1236) ----------------
    {
        "photo_group": "Cent Batch 2 - confident reads", "source_images": "IMG_1233",
        "category": "Circulating Cent (individually read)", "denomination": "1 cent",
        "country": "USA", "year": "2023, 2021, 2021, ~1976",
        "mint_mark": "not legible in photo",
        "design_variety": "Lincoln cents (mix of Lincoln Memorial and Union Shield reverse) laid out on green fabric",
        "coin_spec_key": "Lincoln Cent (Memorial, bronze 1959-1982) / (copper-plated zinc 1982-present)",
        "obverse_text": "LIBERTY / IN GOD WE TRUST + date",
        "reverse_text": "mix of Lincoln Memorial building (1959-2008) and Union Shield (2010-present) reverses",
        "condition_notes": "Good detail, laid on textured fabric (not a hard flat surface), some glare",
        "qty": 4,
        "est_value_low_usd": 0.04, "est_value_high_usd": 0.04,
        "value_basis": "Face value - common modern dates, no premium",
        "confidence": "medium", "notes": "",
    },
    {
        "photo_group": "Cent Batch 2 - unread remainder", "source_images": "IMG_1233",
        "category": "Circulating Cent (bulk, unread)", "denomination": "1 cent",
        "country": "USA", "year": None, "mint_mark": None,
        "design_variety": "Remaining Lincoln cents in the same photo, dates not reliably legible (worn/angled)",
        "coin_spec_key": "Lincoln Cent (Memorial, bronze 1959-1982) / (copper-plated zinc 1982-present)",
        "obverse_text": "LIBERTY / IN GOD WE TRUST + date",
        "reverse_text": "mix of Lincoln Memorial and Union Shield reverses",
        "condition_notes": "A couple show heavier wear; one coin's date sits right at a fold in the fabric",
        "qty": 7,
        "est_value_low_usd": 0.07, "est_value_high_usd": 0.20,
        "value_basis": "Face value expected; all appear to be common modern-date memorial/shield cents, no wheat cents spotted in this batch",
        "confidence": "low", "notes": "",
    },
    {
        "photo_group": "Cent Batch 2 - anomalous gold-toned cent", "source_images": "IMG_1233",
        "category": "Circulating Cent (individually read)", "denomination": "1 cent",
        "country": "USA", "year": None, "mint_mark": None,
        "design_variety": "Union Shield cent (2010-present) with unusual overall brass/gold coloring instead of normal copper-red",
        "coin_spec_key": "Lincoln Cent (Memorial/Shield, copper-plated zinc 1982-present)",
        "obverse_text": "not photographed in this crop",
        "reverse_text": "ONE CENT / E PLURIBUS UNUM / UNITED STATES OF AMERICA - shield design, brassy-gold tone",
        "condition_notes": "Distinct yellow/gold tone across the whole coin, unlike the reddish-brown of the others next to it",
        "qty": 1,
        "est_value_low_usd": 0.01, "est_value_high_usd": 1,
        "value_basis": "Face value - the color shift is almost certainly heat/chemical discoloration (the copper plating thins or reacts, exposing more of the zinc core's tone) or a novelty gold-dipped souvenir cent, not a mint error or plating variety with real premium",
        "confidence": "medium",
        "notes": "If you want to be sure, a genuine mint error (like a wrong-planchet or unplated cent) would be worth checking with a coin dealer, but the most common explanation for an evenly gold-toned modern cent is environmental exposure (e.g. went through a dryer, was near a chemical, or sat in acidic soil) - which does not add value.",
    },
    {
        "photo_group": "Nickel Batch 2", "source_images": "IMG_1234, IMG_1235, IMG_1236",
        "category": "Circulating Nickel", "denomination": "5 cents",
        "country": "USA", "year": "2022 (P)", "mint_mark": "P",
        "design_variety": "Jefferson Nickel, \"Return to Monticello\" design (2006-present)",
        "coin_spec_key": "Jefferson Nickel",
        "obverse_text": "IN GOD WE TRUST / Liberty (script signature) / 2022 P",
        "reverse_text": "MONTICELLO / E PLURIBUS UNUM / UNITED STATES OF AMERICA / FIVE CENTS",
        "condition_notes": "Lightly circulated, good detail, clearly dated",
        "qty": 1,
        "est_value_low_usd": 0.05, "est_value_high_usd": 0.05,
        "value_basis": "Face value - common date/mintmark",
        "confidence": "high", "notes": "",
    },
    {
        "photo_group": "Nickel Batch 2 - worn pair", "source_images": "IMG_1234, IMG_1235, IMG_1236",
        "category": "Circulating Nickel", "denomination": "5 cents",
        "country": "USA", "year": None, "mint_mark": "not legible in photo",
        "design_variety": "2x Jefferson Nickel, older classic design, dates worn/photo too blurry to read",
        "coin_spec_key": "Jefferson Nickel",
        "obverse_text": "LIBERTY / IN GOD WE TRUST (arched pre-2004 style lettering)",
        "reverse_text": "MONTICELLO / E PLURIBUS UNUM / UNITED STATES OF AMERICA / FIVE CENTS",
        "condition_notes": "Moderate wear; reverse photos (IMG_1235/1236) are motion-blurred, dates not recoverable from these images",
        "qty": 2,
        "est_value_low_usd": 0.10, "est_value_high_usd": 0.10,
        "value_basis": "Face value expected for common worn Jefferson nickels; re-photograph in focus if you want exact dates",
        "confidence": "low", "notes": "",
    },

    # ---------------- BATCH 3 (IMG_1237-1240) - large scattered spread on green fabric ----------------
    {
        "photo_group": "Big Spread - cents, confident reads", "source_images": "IMG_1237, IMG_1238, IMG_1239, IMG_1240",
        "category": "Circulating Cent (individually read)", "denomination": "1 cent",
        "country": "USA", "year": "2015, 2016, 2019, 2020, 2021, 2021, 2023, 2004, 2009, 1990, 1986, 1995, 2013",
        "mint_mark": "not legible in photo",
        "design_variety": "Lincoln cents (mix of Lincoln Memorial and Union Shield reverse) scattered across a green quilted fabric",
        "coin_spec_key": "Lincoln Cent (Memorial, bronze 1959-1982) / (copper-plated zinc 1982-present)",
        "obverse_text": "LIBERTY / IN GOD WE TRUST + date",
        "reverse_text": "mix of Lincoln Memorial building and Union Shield reverses; one clear \"ONE CENT / UNITED STATES OF AMERICA\" shield reverse",
        "condition_notes": "Good lighting/detail on these, no wheat cents (pre-1959) spotted in this batch",
        "qty": 13,
        "est_value_low_usd": 0.13, "est_value_high_usd": 0.13,
        "value_basis": "Face value - all common modern dates, no premium",
        "confidence": "high", "notes": "",
    },
    {
        "photo_group": "Big Spread - cents, unread remainder", "source_images": "IMG_1237, IMG_1238, IMG_1239, IMG_1240",
        "category": "Circulating Cent (bulk, possible duplicate photos)", "denomination": "1 cent",
        "country": "USA", "year": None, "mint_mark": None,
        "design_variety": "Additional Lincoln cents visible across these 4 photos, dates not confidently read or likely repeated between overlapping shots",
        "coin_spec_key": "Lincoln Cent (Memorial, bronze 1959-1982) / (copper-plated zinc 1982-present)",
        "obverse_text": "LIBERTY / IN GOD WE TRUST + date",
        "reverse_text": "mix of Lincoln Memorial and Union Shield reverses",
        "condition_notes": "These 4 photos appear to be overlapping shots of ONE large scattered coin spread (same green quilted fabric, matching coins visible near the edges of adjacent frames), not 4 separate piles",
        "qty": 20,
        "est_value_low_usd": 0.20, "est_value_high_usd": 0.20,
        "value_basis": "Face value expected - no wheat cents or unusual dates spotted",
        "confidence": "low",
        "notes": "Treat this as one estimate for the whole spread, not 4x the visible coins - recommend a physical recount since the same coins likely appear in more than one of these 4 overlapping photos.",
    },
    {
        "photo_group": "Big Spread - nickels, confident reads", "source_images": "IMG_1237, IMG_1238, IMG_1239, IMG_1240",
        "category": "Circulating Nickel", "denomination": "5 cents",
        "country": "USA", "year": "2022, 2016, 2009", "mint_mark": "not legible in photo",
        "design_variety": "Jefferson Nickel, \"Return to Monticello\" design (2006-present, script \"Liberty\")",
        "coin_spec_key": "Jefferson Nickel",
        "obverse_text": "IN GOD WE TRUST / Liberty (script) + date",
        "reverse_text": "not the focus of these photos (obverse-up)",
        "condition_notes": "Clear, lightly circulated",
        "qty": 3,
        "est_value_low_usd": 0.15, "est_value_high_usd": 0.15,
        "value_basis": "Face value - common dates",
        "confidence": "high", "notes": "",
    },
    {
        "photo_group": "Big Spread - nickels, older/unread", "source_images": "IMG_1237, IMG_1238, IMG_1239, IMG_1240",
        "category": "Circulating Nickel", "denomination": "5 cents",
        "country": "USA", "year": None, "mint_mark": "not legible in photo",
        "design_variety": "Additional Jefferson Nickels, mix of older arched-\"LIBERTY\" pre-2004 design and newer script design, dates not legible",
        "coin_spec_key": "Jefferson Nickel",
        "obverse_text": "LIBERTY / IN GOD WE TRUST + date (not legible)",
        "reverse_text": "not photographed",
        "condition_notes": "Several look moderately worn with a duller/darker tone - worth a quick check for 1942-1945 \"war nickels\" (35% silver, large mint mark over Monticello dome) since worn old-style Jefferson nickels are in the mix",
        "qty": 6,
        "est_value_low_usd": 0.30, "est_value_high_usd": 5,
        "value_basis": "Face value if standard copper-nickel; ~$1.50+ each in silver melt alone if any turn out to be 1942-1945 war nickels",
        "confidence": "low",
        "notes": "Quick tell for a war nickel: flip it over - if the mint mark letter (P, D, or S) is large and sits directly above Monticello's dome (instead of the usual small mark to the right), it's 35% silver.",
    },
    {
        "photo_group": "Big Spread - dimes", "source_images": "IMG_1237, IMG_1238, IMG_1239, IMG_1240",
        "category": "Circulating Dime", "denomination": "10 cents",
        "country": "USA", "year": None, "mint_mark": "not legible in photo",
        "design_variety": "Roosevelt Dimes, various, scattered in the same spread",
        "coin_spec_key": "Roosevelt Dime (clad, 1965-present)",
        "obverse_text": "LIBERTY / IN GOD WE TRUST",
        "reverse_text": "not photographed close enough to read",
        "condition_notes": "Glare on a couple of these obscures the date",
        "qty": 7,
        "est_value_low_usd": 0.70, "est_value_high_usd": 15,
        "value_basis": "Face value if clad; ~$2+ each in silver melt if any are 1964-or-earlier (90% silver) - same check as the other 13 dimes in this collection",
        "confidence": "low",
        "notes": "Same silver-date check applies here as the other dime group - see notes on \"Dimes (13)\".",
    },
]
