# Reference list of U.S. coin key dates / varieties worth flagging for a closer
# look. This is not an appraisal - it's a cheap first-pass filter so a handful
# of candidates get pulled out of a big bag instead of everything being
# treated as "probably common."
#
# Two tiers of rules:
#   1. Data-driven (mintage_data.py, generated by build_mintage_table.py) -
#      key dates derived from published mintage figures, ranked *within* each
#      series. Covers whatever series have been exported so far.
#   2. Hand-written RULES below - the modern circulating series (silver cutoffs,
#      war nickels, wheat cents) where the rule is about composition/era rather
#      than mintage.

try:
    from mintage_data import MINTAGE
except ImportError:  # table not generated yet - hand rules still work
    MINTAGE = {}

KEY_PCT = 0.10     # rarest 10% of a series' dates -> "key date"
SCARCE_PCT = 0.25  # rarest 25% -> "scarce"

_SERIES = sorted({k[0] for k in MINTAGE}, key=len, reverse=True)

KEY_DATE_CENTS = {
    "1909-S VDB", "1909-S", "1914-D", "1922 (no mintmark/plain)",
    "1931-S", "1943 (bronze - should be steel, extremely rare error)",
    "1943 (steel - normal for that year)", "1955 (doubled die obverse)",
    "1972 (doubled die obverse)", "1969-S (doubled die obverse)",
}

RULES = [
    # Checked before the per-denomination rules: a pre-1965 set is silver because
    # of what's inside it, and deserves a reason that says so.
    {
        "test": lambda row: str(row.get("category", "")) in ("Proof Set", "Mint Set")
        and _year_num(row.get("year")) and _year_num(row["year"]) <= 1964,
        "reason": "Pre-1965 U.S. Proof/Mint Set - the dime, quarter and half dollar inside are all 90% silver, so the set carries real melt value on top of any collector premium. Keep it sealed and intact; breaking a set up usually lowers what it's worth.",
    },
    {
        "test": lambda row: row["category"] == "Circulating Cent" and row.get("wheat_reverse"),
        "reason": "Wheat-reverse cent (1909-1958) - worth pulling aside and checking the exact date/mintmark against the key-date list (1909-S VDB, 1909-S, 1914-D, 1922 plain, 1931-S, 1955 DDO) before assuming it's common.",
    },
    {
        "test": lambda row: row["category"] == "Circulating Dime" and row.get("year") and _year_num(row["year"]) and _year_num(row["year"]) <= 1964,
        "reason": "Dated 1964 or earlier - U.S. dimes this age (Barber/Mercury/Roosevelt alike) are 90% silver, worth several dollars in melt value alone regardless of grade.",
    },
    {
        "test": lambda row: row["category"] == "Circulating Quarter" and row.get("year") and _year_num(row["year"]) and _year_num(row["year"]) <= 1964,
        "reason": "Dated 1964 or earlier - U.S. quarters this age (Barber/Standing Liberty/Washington alike) are 90% silver.",
    },
    {
        "test": lambda row: row["category"] == "Circulating Nickel" and row.get("year") and _year_num(row["year"]) in (1942, 1943, 1944, 1945),
        "reason": "1942-1945 Jefferson nickels were struck in 35% silver (\"war nickels\") - check for a large mintmark over Monticello's dome.",
    },
    {
        "test": lambda row: _is_half_dollar(row) and _year_num(row.get("year")) and _year_num(row["year"]) <= 1964,
        "reason": "Half dollar dated 1964 or earlier (1964 Kennedy, Franklin, Walking Liberty, Barber) - 90% silver. Worth many times face in melt value alone, regardless of grade.",
    },
    {
        "test": lambda row: _is_half_dollar(row) and _year_num(row.get("year")) and 1965 <= _year_num(row["year"]) <= 1970,
        "reason": "Kennedy half dated 1965-1970 - 40% silver (silver-clad). These are the ones people miss: they look like ordinary clad halves but still carry real melt value. Do not spend it.",
    },
]


def _year_num(year_field):
    try:
        return int(str(year_field).strip()[:4])
    except (ValueError, TypeError):
        return None


def _is_half_dollar(row):
    """Half dollars can arrive labelled by category, denomination, or just the
    design ('Kennedy Half Dollar'), so check all three."""
    text = " ".join(
        str(row.get(k, "") or "") for k in ("category", "denomination", "design_variety")
    ).lower()
    return "half dollar" in text or "half-dollar" in text


def _ordinal(n):
    if 10 <= n % 100 <= 20:
        suffix = "th"
    else:
        suffix = {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")
    return f"{n}{suffix}"


def _series_of(row):
    """Infer which catalogued series a row belongs to, by matching every word of
    a series name against the row's free-text fields. Longest name wins, so
    'Barber Half Dollar' beats a looser partial."""
    text = " ".join(
        str(row.get(k, "")) for k in ("design_variety", "category", "denomination")
    ).lower()
    for series in _SERIES:  # already sorted longest-first
        if all(w in text for w in series.lower().split()):
            return series
    return None


def _mintmark_of(row):
    """Normalize the inventory's mint_mark field, or None if it can't be read.
    Most bag photos can't resolve a mintmark, which is what the fallback rule
    in _mintage_flag() exists for."""
    raw = str(row.get("mint_mark", "") or "").strip()
    if not raw or "legible" in raw.lower():
        return None
    low = raw.lower()
    if "none" in low or "philadelphia" in low:
        return "P"
    upper = raw.upper()
    for mm in ("CC", "D", "S", "O", "P", "W"):  # CC before C-initial singles
        if upper.startswith(mm):
            return mm
    return None


def _mintage_flag(row):
    """Key-date / scarce-date check driven by published mintage figures."""
    series = _series_of(row)
    year = _year_num(row.get("year"))
    if not series or not year:
        return ""

    mint = _mintmark_of(row)
    if mint:
        hit = MINTAGE.get((series, year, mint))
        if not hit:
            return ""
        mintage, rank, size = hit
        if rank / size <= KEY_PCT:
            return (
                f"KEY DATE: {year}-{mint} {series} - mintage {mintage:,}, the "
                f"{_ordinal(rank)} lowest of {size} dates in the series. Get it "
                "authenticated/graded before doing anything with it."
            )
        if rank / size <= SCARCE_PCT:
            return (
                f"Scarce date: {year}-{mint} {series} - mintage {mintage:,} "
                f"({_ordinal(rank)} lowest of {size} dates). Worth a closer look."
            )
        return ""

    # Mintmark unreadable (the common case in bag photos): if ANY mint struck a
    # key date that year, the mintmark is the difference between common and rare.
    keys = [(k, v) for k, v in MINTAGE.items() if k[0] == series and k[1] == year]
    hits = sorted(
        ((k[2], v[0]) for k, v in keys if v[1] / v[2] <= KEY_PCT),
        key=lambda h: h[1],
    )
    if hits:
        listed = ", ".join(f"{year}-{mm} (mintage {mg:,})" for mm, mg in hits)
        return (
            f"Mintmark not legible - CHECK IT. For {year} {series} these mints are "
            f"key dates: {listed}. The same year from another mint can be common, so "
            "the mintmark decides whether this is worth a lot or a little."
        )
    return ""


def flag(row):
    """Return (is_flagged, reason) for an inventory row dict."""
    # Mintage-driven key dates are more specific than the era/composition rules,
    # so they take precedence.
    reason = _mintage_flag(row)
    if reason:
        return True, reason

    for rule in RULES:
        try:
            if rule["test"](row):
                return True, rule["reason"]
        except Exception:
            continue
    return False, ""
