# Labels for the two well-labeled tiers of training/ - filename already tells
# us the class, so these were parsed by hand from the filename rather than
# visually re-derived like training_labels.LABELS (the unlabeled fs.jpg set).

# One reference image per historical design era/series (spans a range of
# years, not a single date) - dime/quarter/half-dollar/dollar type set.
SERIES_LABELS = [
    dict(file="0000029_draped-bust-dimes.png", series="Draped Bust", denomination="Dime", years="1796-1807"),
    dict(file="0000030_capped-bust-dimes.png", series="Capped Bust", denomination="Dime", years="1809-1837"),
    dict(file="0000031_liberty-seated-dimes.png", series="Seated Liberty", denomination="Dime", years="1837-1891"),
    dict(file="0000032_barber-dimes.png", series="Barber", denomination="Dime", years="1892-1916"),
    dict(file="0000033_mercury-dimes.png", series="Mercury (Winged Liberty Head)", denomination="Dime", years="1916-1945"),
    dict(file="0000035_draped-bust-quarters.png", series="Draped Bust", denomination="Quarter", years="1796-1807"),
    dict(file="0000036_capped-bust-quarters.png", series="Capped Bust", denomination="Quarter", years="1815-1838"),
    dict(file="0000037_liberty-seated-quarters.png", series="Seated Liberty", denomination="Quarter", years="1838-1891"),
    dict(file="0000038_barber-quarters.png", series="Barber", denomination="Quarter", years="1892-1916"),
    dict(file="0000039_standing-liberty-quarters.png", series="Standing Liberty", denomination="Quarter", years="1916-1930"),
    dict(file="0000040_flowing-hair-half-dollars.png", series="Flowing Hair", denomination="Half Dollar", years="1794-1795"),
    dict(file="0000041_draped-bust-half-dollars.png", series="Draped Bust", denomination="Half Dollar", years="1796-1807"),
    dict(file="0000042_capped-bust-half-dollars.png", series="Capped Bust", denomination="Half Dollar", years="1807-1839"),
    dict(file="0000043_liberty-seated-half-dollars.png", series="Seated Liberty", denomination="Half Dollar", years="1839-1891"),
    dict(file="0000044_barber-half-dollars.png", series="Barber", denomination="Half Dollar", years="1892-1915"),
    dict(file="0000045_walking-liberty-half-dollars.png", series="Walking Liberty", denomination="Half Dollar", years="1916-1947"),
    dict(file="0000046_flowing-hair-dollars.png", series="Flowing Hair", denomination="Dollar", years="1794-1795"),
    dict(file="0000047_draped-bust-dollars.png", series="Draped Bust", denomination="Dollar", years="1795-1804"),
    dict(file="0000048_liberty-seated-dollars.png", series="Seated Liberty", denomination="Dollar", years="1840-1873"),
    dict(file="0000049_trade-dollars.png", series="Trade Dollar", denomination="Dollar", years="1873-1885"),
    dict(file="0000050_morgan-dollars.png", series="Morgan Dollar", denomination="Dollar", years="1878-1921"),
    dict(file="0000051_peace-dollars.png", series="Peace Dollar", denomination="Dollar", years="1921-1935"),
]

# Modern bullion/proof/commemorative products - obverse+reverse pairs, mostly
# 2023-2025 U.S. Mint releases plus a couple of historic gold references.
NAMED_LABELS = [
    dict(file="1804-dollar-gold-obverse.jpg", series="1804 Gold Dollar (pattern/restrike reference)", side="obverse", year=1804),
    dict(file="1804-dollar-gold-reverse.jpg", series="1804 Gold Dollar (pattern/restrike reference)", side="reverse", year=1804),
    dict(file="1907-saint-gaudens-semiq-gold-obverse.jpg", series="Saint-Gaudens $2.50 gold pattern reference", side="obverse", year=1907),
    dict(file="1907-saint-gaudens-semiq-gold-reverse.jpg", series="Saint-Gaudens $2.50 gold pattern reference", side="reverse", year=1907),
    dict(file="2023-american-eagle-palladium-one-ounce-bullion-coin-obverse.jpg", series="American Eagle Palladium Bullion", side="obverse", year=2023),
    dict(file="2023-american-eagle-palladium-one-ounce-bullion-coin-reverse.jpg", series="American Eagle Palladium Bullion", side="reverse", year=2023),
    dict(file="2023-american-eagle-palladium-one-ounce-uncirculated-coin-obverse.jpg", series="American Eagle Palladium Uncirculated", side="obverse", year=2023),
    dict(file="2023-american-eagle-palladium-one-ounce-uncirculated-coin-reverse.jpg", series="American Eagle Palladium Uncirculated", side="reverse", year=2023),
    dict(file="2023-american-eagle-platinum-one-ounce-bullion-coin-obverse.jpg", series="American Eagle Platinum Bullion", side="obverse", year=2023),
    dict(file="2023-american-eagle-platinum-one-ounce-bullion-coin-reverse.jpg", series="American Eagle Platinum Bullion", side="reverse", year=2023),
    dict(file="2024-american-eagle-palladium-one-ounce-proof-coin-obverse.jpg", series="American Eagle Palladium Proof", side="obverse", year=2024),
    dict(file="2024-american-eagle-palladium-one-ounce-proof-coin-reverse.jpg", series="American Eagle Palladium Proof", side="reverse", year=2024),
    dict(file="2025 American Liberty 1oz Gold Obv 2000x2000.jpg", series="American Liberty 1oz Gold", side="obverse", year=2025),
    dict(file="2025 American Liberty 1oz Gold Rev 2000x2000.jpg", series="American Liberty 1oz Gold", side="reverse", year=2025),
    dict(file="2025-Batman-Gold-Proof-Coin-Obverse.jpg", series="Batman Commemorative Gold Proof", side="obverse", year=2025),
    dict(file="2025-Batman-Gold-Proof-Coin-Reverse.jpg", series="Batman Commemorative Gold Proof", side="reverse", year=2025),
    dict(file="2025-Morgan-Proof-Obverse.jpg", series="Morgan Dollar Proof (modern reissue)", side="obverse", year=2025),
    dict(file="2025-Morgan-Proof-Reverse.jpg", series="Morgan Dollar Proof (modern reissue)", side="reverse", year=2025),
    dict(file="2025-Morgan-Unc-Obverse.jpg", series="Morgan Dollar Uncirculated (modern reissue)", side="obverse", year=2025),
    dict(file="2025-Morgan-Unc-Reverse.jpg", series="Morgan Dollar Uncirculated (modern reissue)", side="reverse", year=2025),
    dict(file="2025-Peace-Proof-Obverse.jpg", series="Peace Dollar Proof (modern reissue)", side="obverse", year=2025),
    dict(file="2025-Peace-Proof-Reverse.jpg", series="Peace Dollar Proof (modern reissue)", side="reverse", year=2025),
    dict(file="2025-Peace-Unc-Obverse.jpg", series="Peace Dollar Uncirculated (modern reissue)", side="obverse", year=2025),
    dict(file="2025-Peace-Unc-Reverse.jpg", series="Peace Dollar Uncirculated (modern reissue)", side="reverse", year=2025),
    dict(file="2025-Superman-Gold-Obverse.jpg", series="Superman Commemorative Gold", side="obverse", year=2025),
    dict(file="2025-Superman-Gold-Reverse.jpg", series="Superman Commemorative Gold", side="reverse", year=2025),
    dict(file="2025-Wonder-Woman-Gold-Proof-Coin-Obverse.jpg", series="Wonder Woman Commemorative Gold Proof", side="obverse", year=2025),
    dict(file="2025-Wonder-Woman-Gold-Proof-Coin-Reverse.jpg", series="Wonder Woman Commemorative Gold Proof", side="reverse", year=2025),
    dict(file="2025-american-buffalo-one-ounce-gold-proof-coin-obverse.jpg", series="American Buffalo Gold Proof", side="obverse", year=2025),
    dict(file="2025-american-buffalo-one-ounce-gold-proof-coin-reverse.jpg", series="American Buffalo Gold Proof", side="reverse", year=2025),
    dict(file="2025-american-eagle-gold-one-ounce-proof-coin-obverse.jpg", series="American Eagle Gold Proof", side="obverse", year=2025),
    dict(file="2025-american-eagle-gold-one-ounce-proof-coin-reverse.jpg", series="American Eagle Gold Proof", side="reverse", year=2025),
    dict(file="2025-american-eagle-gold-one-ounce-uncirculated-coin-obverse.jpg", series="American Eagle Gold Uncirculated", side="obverse", year=2025),
    dict(file="2025-american-eagle-gold-one-ounce-uncirculated-coin-reverse.jpg", series="American Eagle Gold Uncirculated", side="reverse", year=2025),
    dict(file="2025-american-eagle-laser-privy-silver-proof-obverse.jpg", series="American Eagle Silver Proof (Laser Privy)", side="obverse", year=2025),
    dict(file="2025-american-eagle-laser-privy-silver-proof-reverse.jpg", series="American Eagle Silver Proof (Laser Privy)", side="reverse", year=2025),
    dict(file="2025-american-eagle-palladium-reverse-proof-obverse.jpg", series="American Eagle Palladium Reverse Proof", side="obverse", year=2025),
    dict(file="2025-american-eagle-palladium-reverse-proof-reverse.jpg", series="American Eagle Palladium Reverse Proof", side="reverse", year=2025),
    dict(file="2025-american-eagle-platinum-proof-coin-obverse.jpg", series="American Eagle Platinum Proof", side="obverse", year=2025),
    dict(file="2025-american-eagle-platinum-proof-coin-reverse.jpg", series="American Eagle Platinum Proof", side="reverse", year=2025),
    dict(file="2025-american-eagle-silver-one-ounce-uncirculated-coin-obverse.jpg", series="American Eagle Silver Uncirculated", side="obverse", year=2025),
    dict(file="2025-american-eagle-silver-one-ounce-uncirculated-coin-reverse.jpg", series="American Eagle Silver Uncirculated", side="reverse", year=2025),
    dict(file="2025-american-eagle-silver-proof-army-privy-obverse.jpg", series="American Eagle Silver Proof (Army Privy)", side="obverse", year=2025),
    dict(file="2025-american-eagle-silver-proof-army-privy-reverse.jpg", series="American Eagle Silver Proof (Army Privy)", side="reverse", year=2025),
    dict(file="2025-american-eagle-silver-proof-navy-privy-obverse.jpg", series="American Eagle Silver Proof (Navy Privy)", side="obverse", year=2025),
    dict(file="2025-american-eagle-silver-proof-navy-privy-reverse.jpg", series="American Eagle Silver Proof (Navy Privy)", side="reverse", year=2025),
    dict(file="2025-american-eagle-silver-proof-usmc-privy-obverse.jpg", series="American Eagle Silver Proof (USMC Privy)", side="obverse", year=2025),
    dict(file="2025-american-eagle-silver-proof-usmc-privy-reverse.jpg", series="American Eagle Silver Proof (USMC Privy)", side="reverse", year=2025),
    dict(file="2025-native-american-one-dollar-uncirculated-coin-obverse.jpg", series="Native American $1 Uncirculated", side="obverse", year=2025),
    dict(file="2025-native-american-one-dollar-uncirculated-coin-reverse.jpg", series="Native American $1 Uncirculated", side="reverse", year=2025),
    dict(file="AE-Gold-Enhanced-Unc-Obverse.jpg", series="American Eagle Gold Enhanced Uncirculated", side="obverse", year=None),
    dict(file="AE-Gold-Enhanced-Unc-Reverse.jpg", series="American Eagle Gold Enhanced Uncirculated", side="reverse", year=None),
    dict(file="AE-Silver-Enhanced-Unc-Obverse.jpg", series="American Eagle Silver Enhanced Uncirculated", side="obverse", year=None),
    dict(file="AE-Silver-Enhanced-Unc-Reverse.jpg", series="American Eagle Silver Enhanced Uncirculated", side="reverse", year=None),
    dict(file="AE-Silver-Proof-Obverse.jpg", series="American Eagle Silver Proof", side="obverse", year=None),
    dict(file="AE-Silver-Proof-Reverse.jpg", series="American Eagle Silver Proof", side="reverse", year=None),
    dict(file="American-Buffalo-Gold-Bullion-Obverse.jpg", series="American Buffalo Gold Bullion", side="obverse", year=None),
    dict(file="American-Buffalo-Gold-Bullion-Reverse.jpg", series="American Buffalo Gold Bullion", side="reverse", year=None),
    dict(file="American-Buffalo-Proof-Gold-Obverse.jpg", series="American Buffalo Gold Proof", side="obverse", year=None),
    dict(file="American-Buffalo-Proof-Gold-Reverse.jpg", series="American Buffalo Gold Proof", side="reverse", year=None),
    dict(file="American-Eagle-Gold-Bullion-1oz-Obverse.jpg", series="American Eagle Gold Bullion (1oz)", side="obverse", year=None),
    dict(file="American-Eagle-Gold-Bullion-1oz-Reverse.jpg", series="American Eagle Gold Bullion (1oz)", side="reverse", year=None),
    dict(file="American-Eagle-Gold-Proof-Obverse.jpg", series="American Eagle Gold Proof", side="obverse", year=None),
    dict(file="American-Eagle-Gold-Proof-Reverse.jpg", series="American Eagle Gold Proof", side="reverse", year=None),
    dict(file="American-Eagle-Palladium-Unc-Obverse.jpg", series="American Eagle Palladium Uncirculated", side="obverse", year=None),
    dict(file="American-Eagle-Palladium-Unc-Reverse.jpg", series="American Eagle Palladium Uncirculated", side="reverse", year=None),
    dict(file="American-Eagle-Platinum-Proof-Obverse.jpg", series="American Eagle Platinum Proof", side="obverse", year=None),
    dict(file="American-Eagle-Platinum-Proof-Reverse.jpg", series="American Eagle Platinum Proof", side="reverse", year=None),
    dict(file="American-Eagle-Silver-Bullion-Obverse.jpg", series="American Eagle Silver Bullion", side="obverse", year=None),
    dict(file="American-Eagle-Silver-Bullion-Reverse.jpg", series="American Eagle Silver Bullion", side="reverse", year=None),
    dict(file="American-Eagle-Silver-Proof-Privy-Obverse.jpg", series="American Eagle Silver Proof (Privy Mark)", side="obverse", year=None),
    dict(file="American-Eagle-Silver-Proof-Privy-Reverse.jpg", series="American Eagle Silver Proof (Privy Mark)", side="reverse", year=None),
    dict(file="American-Innovation-Unc-Obverse.jpg", series="American Innovation Dollar", side="obverse (shared across all states)", year=None),
    dict(file="American-Innovation-Unc-Reverse-California.jpg", series="American Innovation Dollar - California", side="reverse", year=None),
    dict(file="American-Innovation-Unc-Reverse-Iowa.jpg", series="American Innovation Dollar - Iowa", side="reverse", year=None),
    dict(file="American-Innovation-Unc-Reverse-Minnesota.jpg", series="American Innovation Dollar - Minnesota", side="reverse", year=None),
    dict(file="American-Innovation-Unc-Reverse-Wisconsin.jpg", series="American Innovation Dollar - Wisconsin", side="reverse", year=None),
]
