# Visual identification labels for training/######fs.jpg reference photos.
# Rows marked "Confirmed via dealer listing" were cross-checked against
# training/coins.csv (a scrape of rarecoinwholesalers.com product listings
# whose SKUs match our fs.jpg numeric filenames) via reconcile_fs_labels.py -
# these are ground truth, not a visual guess. Everything else is still a
# best-effort visual read (see confidence).

LABELS = [
    dict(file='115168fs.jpg', series='Liberty Seated', denomination='uncertain (dime/quarter/half)', year=1844, confidence='medium', notes='Shield-and-branch Seated Liberty obverse; denomination not visible in this crop.'),
    dict(file='120703fs.jpg', series='Draped Bust', denomination='Dime', year=1801, confidence='high', notes='Confirmed via dealer listing (SKU 120703): "1801 draped bust 10c ms61".'),
    dict(file='121514fs.jpg', series='Seated Liberty / Trade Dollar style', denomination='Dollar (likely Trade Dollar)', year=1878, confidence='low', notes='Full-figure seated Liberty with pole/cap; 1878 postdates the regular Seated Dollar series (ended 1873), suggesting Trade Dollar.'),
    dict(file='121564fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1899, confidence='medium', notes='"IN GOD WE TRUST" arch present, rules out Barber dime.'),
    dict(file='122773fs.jpg', series='Seated Liberty / Trade Dollar style', denomination='Dollar (likely Trade Dollar)', year=1877, confidence='low', notes='Same style as 121514fs; 1877 is within the Trade Dollar era.'),
    dict(file='124971fs.jpg', series='Draped Bust', denomination='Half Dollar', year=1806, confidence='high', notes='Confirmed via dealer listing (SKU 124971): "1806 draped bust 50c pointed 6 stem large eagle".'),
    dict(file='128257fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1832, confidence='high', notes=''),
    dict(file='129606fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1898, confidence='medium', notes='"IN GOD WE TRUST" arch present.'),
    dict(file='133070fs.jpg', series='Barber-style Liberty head', denomination='uncertain', year=None, confidence='low', notes='Date largely illegible, appears to read ~189X.'),
    dict(file='133077fs.jpg', series='Seated Liberty', denomination='Dollar (likely)', year=1857, confidence='medium', notes='Full-figure seated design with flag/pole, large size consistent with a dollar.'),
    dict(file='134155fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1814, confidence='high', notes=''),
    dict(file='134255fs.jpg', series='Draped Bust', denomination='Dime', year=1798, confidence='high', notes='Confirmed via dealer listing (SKU 134255): "1798 draped bust 10c large 8 ms64".'),
    dict(file='134407fs.jpg', series='Capped Bust', denomination='Quarter', year=1818, confidence='high', notes='Confirmed via dealer listing (SKU 134407): "1818 capped bust 25c ms66 plus".'),
    dict(file='134481fs.jpg', series='Morgan', denomination='Dollar', year=1883, confidence='high', notes='Confirmed via dealer listing (SKU 134481): "1883 morgan s1 ms66 dmpl".'),
    dict(file='134498fs.jpg', series='Seated Liberty (Arrows)', denomination='uncertain (quarter/half)', year=1874, confidence='medium', notes='Arrows at date typical of the 1873-1874 weight-standard change.'),
    dict(file='134672fs.jpg', series='Morgan', denomination='Dollar', year=1890, confidence='high', notes='Confirmed via dealer listing (SKU 134672): "1890 morgan s1 ms65 dmpl".'),
    dict(file='134720fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1840, confidence='medium', notes=''),
    dict(file='134729fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1859, confidence='medium', notes=''),
    dict(file='134864fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1842, confidence='medium', notes=''),
    dict(file='134872fs.jpg', series='Capped Bust', denomination='uncertain (half/quarter)', year=1840, confidence='low', notes='Date partially legible.'),
    dict(file='135367fs.jpg', series='Flowing Hair', denomination='Half Dollar', year=1794, confidence='high', notes='Confirmed via dealer listing (SKU 135367): "1794 flowing hair 50c au55".'),
    dict(file='135616fs.jpg', series='Capped Bust', denomination='Dime', year=1820, confidence='high', notes='Confirmed via dealer listing (SKU 135616): "1820 capped bust 10c small 0 ms67".'),
    dict(file='135641fs.jpg', series='Barber', denomination='uncertain (quarter/half/dime)', year=1896, confidence='medium', notes=''),
    dict(file='135652fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half/dollar)', year=1868, confidence='medium', notes=''),
    dict(file='135760fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1840, confidence='medium', notes=''),
    dict(file='135761fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1850, confidence='medium', notes=''),
    dict(file='135762fs.jpg', series='Liberty Seated', denomination='Quarter', year=1843, confidence='high', notes='Confirmed via dealer listing (SKU 135762): "1843 liberty seated 25c pr64".'),
    dict(file='135764fs.jpg', series='Panama-Pacific Commemorative Gold (octagonal)', denomination='$50 Gold', year=1915, confidence='high', notes='Confirmed via dealer listing (SKU 135764): "1915 s gold 50 pan pac octagonal ms65", mint mark S.'),
    dict(file='135780fs.jpg', series='Capped Bust', denomination='uncertain (half/quarter)', year=None, confidence='low', notes='Date partially legible, appears to be 182X.'),
    dict(file='135873fs.jpg', series='Flowing Hair', denomination='Half Dollar', year=1795, confidence='high', notes='Confirmed via dealer listing (SKU 135873): "1795 flowing hair 50c ms62 plus".'),
    dict(file='136298fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half/dollar)', year=1865, confidence='medium', notes=''),
    dict(file='136828fs.jpg', series='Walking Liberty', denomination='Half Dollar', year=1917, confidence='high', notes='Distinctive full-figure walking Liberty design.'),
    dict(file='136838fs.jpg', series='Draped Bust', denomination='Quarter', year=1806, confidence='high', notes='Confirmed via dealer listing (SKU 136838): "1806 draped bust 25c heraldic eagle ms65".'),
    dict(file='136839fs.jpg', series='Capped Bust', denomination='Quarter', year=1818, confidence='high', notes='Confirmed via dealer listing (SKU 136839): "1818 capped bust 25c ms65".'),
    dict(file='136840fs.jpg', series='Seated Liberty (no-drapery style)', denomination='uncertain (dime/half dime)', year=1845, confidence='medium', notes='Stars fully surround the seated figure, consistent with the smaller no-drapery Seated Liberty dies.'),
    dict(file='136843fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1834, confidence='high', notes=''),
    dict(file='136979fs.jpg', series='Capped Bust', denomination='Quarter', year=1831, confidence='high', notes='Confirmed via dealer listing (SKU 136979): "1831 capped bust 25c small letters ms66".'),
    dict(file='137244fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1839, confidence='medium', notes=''),
    dict(file='137256fs.jpg', series='Capped Bust', denomination='uncertain (likely half dollar)', year=1812, confidence='medium', notes=''),
    dict(file='137442fs.jpg', series='Standing Liberty', denomination='Quarter', year=1917, confidence='high', notes='Distinctive standing Liberty with shield and "IN GOD WE TRUST" - first-year Type 1 (exposed breast) design.'),
    dict(file='137443fs.jpg', series='Capped Bust', denomination='uncertain (likely half dollar)', year=1818, confidence='low', notes='Date partially legible.'),
    dict(file='137457fs.jpg', series='Draped Bust', denomination='uncertain (likely dollar)', year=1798, confidence='low', notes='Date partially legible.'),
    dict(file='137474fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1829, confidence='high', notes=''),
    dict(file='137651fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1830, confidence='high', notes=''),
    dict(file='137663fs.jpg', series='Draped Bust', denomination='Dime', year=1801, confidence='high', notes='Confirmed via dealer listing (SKU 137663): "1801 draped bust 10c ms62".'),
    dict(file='137664fs.jpg', series='Seated Liberty (no-drapery style)', denomination='Dime (likely)', year=1868, confidence='medium', notes=''),
    dict(file='137668fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1890, confidence='medium', notes=''),
    dict(file='138272fs.jpg', series='Draped Bust', denomination='Dime', year=1804, confidence='high', notes='Confirmed via dealer listing (SKU 138272): "1804 draped bust 10c 13 stars reverse xf45".'),
    dict(file='138273fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1821, confidence='high', notes=''),
    dict(file='138345fs.jpg', series='Trade Dollar', denomination='Dollar', year=1876, confidence='high', notes='Distinctive seated-on-bale-of-cotton design with wheat sheaf, extended arm - matches the Trade Dollar type specifically (not the regular Seated Dollar).'),
    dict(file='138611fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1830, confidence='high', notes=''),
    dict(file='138661fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1824, confidence='medium', notes='Date partially legible.'),
    dict(file='138676fs.jpg', series='Seated Liberty (no-drapery style)', denomination='Dime (likely)', year=1869, confidence='medium', notes=''),
    dict(file='138684fs.jpg', series='Draped Bust', denomination='Dime', year=1796, confidence='high', notes='Confirmed via dealer listing (SKU 138684): "1796 draped bust 10c small eagle ms65".'),
    dict(file='138746fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1819, confidence='high', notes=''),
    dict(file='138747fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1829, confidence='high', notes=''),
    dict(file='138768fs.jpg', series='Morgan', denomination='Dollar', year=1881, confidence='high', notes='Confirmed via dealer listing (SKU 138768): "1881 morgan s1 ms65 dmpl".'),
    dict(file='138857fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1905, confidence='low', notes='Date partially legible.'),
    dict(file='138998fs.jpg', series='Seated Liberty / Trade Dollar style', denomination='Dollar', year=1873, confidence='low', notes='Date partially legible.'),
    dict(file='139003fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1856, confidence='medium', notes=''),
    dict(file='139004fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1831, confidence='high', notes=''),
    dict(file='139006fs.jpg', series='Capped Bust', denomination='Dime', year=1821, confidence='high', notes='Confirmed via dealer listing (SKU 139006): "1821 capped bust 10c small date ms66".'),
    dict(file='139109fs.jpg', series='Capped Bust (reduced diameter)', denomination='uncertain (dime/quarter)', year=1825, confidence='medium', notes=''),
    dict(file='139113fs.jpg', series='Capped Bust', denomination='Dime', year=1822, confidence='high', notes='Confirmed via dealer listing (SKU 139113): "1822 capped bust 10c ms65".'),
    dict(file='139351fs.jpg', series='Seated Liberty (Arrows)', denomination='uncertain (quarter/half)', year=1874, confidence='medium', notes=''),
    dict(file='139551fs.jpg', series='Capped Bust', denomination='Quarter', year=1831, confidence='high', notes='Confirmed via dealer listing (SKU 139551): "1831 capped bust 25c small letters ms66".'),
    dict(file='139567fs.jpg', series='Draped Bust', denomination='Dollar', year=1799, confidence='low', notes='Date partially legible.'),
    dict(file='139569fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half/dollar)', year=1845, confidence='medium', notes=''),
    dict(file='139570fs.jpg', series='Draped Bust', denomination='Dime', year=1798, confidence='high', notes='Confirmed via dealer listing (SKU 139570): "1798 draped bust 10c large 8 ms64".'),
    dict(file='139747fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1859, confidence='medium', notes=''),
    dict(file='139871fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1867, confidence='medium', notes=''),
    dict(file='139975fs.jpg', series='Capped Bust', denomination='uncertain (likely half dollar)', year=None, confidence='low', notes='Date not legible.'),
    dict(file='140326fs.jpg', series='Mercury (Winged Liberty Head)', denomination='Dime', year=1916, confidence='medium', notes='Distinctive winged-cap Liberty head + fasces design; exact date digit uncertain.'),
    dict(file='140328fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1859, confidence='low', notes='Date uncertain.'),
    dict(file='140335fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1808, confidence='medium', notes='Date partially legible.'),
    dict(file='140341fs.jpg', series='Draped Bust', denomination='Half Dollar', year=1806, confidence='high', notes='Confirmed via dealer listing (SKU 140341): "1806 draped bust 50c knob 6 no stem f12".'),
    dict(file='140357fs.jpg', series='Seated Liberty (Arrows)', denomination='Quarter (likely)', year=1853, confidence='medium', notes=''),
    dict(file='140368fs.jpg', series='Morgan', denomination='Dollar', year=1882, confidence='high', notes='Confirmed via dealer listing (SKU 140368): "1882 os morgan s1 os strong ms65".'),
    dict(file='140373fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1895, confidence='medium', notes=''),
    dict(file='140376fs.jpg', series='Seated Liberty / Trade Dollar style', denomination='Dollar', year=1885, confidence='low', notes='1885 postdates the regular Seated Dollar series (ended 1873) - if a Trade Dollar, 1885 is an extreme rarity (proof-only); treat with skepticism rather than as a real find.'),
    dict(file='140385fs.jpg', series='Draped Bust', denomination='Dollar', year=1799, confidence='medium', notes=''),
    dict(file='140410fs.jpg', series='Flowing Hair', denomination='Half Dollar', year=1795, confidence='high', notes='Confirmed via dealer listing (SKU 140410): "1795 flowing hair 50c 2 leaves ms62".'),
    dict(file='140580fs.jpg', series='Draped Bust', denomination='uncertain', year=1795, confidence='medium', notes=''),
    dict(file='140585fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1846, confidence='medium', notes=''),
    dict(file='140621fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1852, confidence='medium', notes=''),
    dict(file='140662fs.jpg', series='Seated Liberty / Trade Dollar style', denomination='Dollar', year=1878, confidence='low', notes=''),
    dict(file='140692fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=None, confidence='low', notes='Date not legible.'),
    dict(file='140824fs.jpg', series='Capped Bust (reduced diameter)', denomination='uncertain (dime/quarter)', year=1818, confidence='medium', notes=''),
    dict(file='140825fs.jpg', series='Draped Bust', denomination='Half Dollar', year=1806, confidence='high', notes='Confirmed via dealer listing (SKU 140825): "1806 draped bust 50c pointed 6 stem ms64 plus".'),
    dict(file='140826fs.jpg', series='Seated Liberty (Arrows)', denomination='uncertain (quarter/half)', year=1874, confidence='medium', notes=''),
    dict(file='140834fs.jpg', series='Seated Liberty', denomination='uncertain (dime/half dime)', year=1837, confidence='medium', notes=''),
    dict(file='140868fs.jpg', series='Seated Liberty', denomination='uncertain (half dollar/quarter/dime)', year=1839, confidence='high', notes='Confirmed via dealer listing (SKU 140868): "1839 gobrecht 1 j 104 res pr65".'),
    dict(file='140936fs.jpg', series='Seated Liberty', denomination='uncertain (dime/quarter)', year=1884, confidence='medium', notes=''),
    dict(file='140937fs.jpg', series='Draped Bust', denomination='Dime', year=1805, confidence='high', notes='Confirmed via dealer listing (SKU 140937): "1805 draped bust 10c 4 berries ms67".'),
    dict(file='140974fs.jpg', series='Seated Liberty (Arrows)', denomination='uncertain (quarter/half)', year=1873, confidence='medium', notes=''),
    dict(file='141155fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1850, confidence='medium', notes=''),
    dict(file='141216fs.jpg', series='Draped Bust', denomination='Dime', year=1803, confidence='high', notes='Confirmed via dealer listing (SKU 141216): "1803 draped bust 10c ms61".'),
    dict(file='141225fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1866, confidence='medium', notes=''),
    dict(file='141228fs.jpg', series='Capped Bust', denomination='Quarter', year=1820, confidence='high', notes='Confirmed via dealer listing (SKU 141228): "1820 capped bust 25c large 0 ms63".'),
    dict(file='141619fs.jpg', series='Barber', denomination='Half Dollar (likely)', year=1903, confidence='medium', notes=''),
    dict(file='141915fs.jpg', series='Seated Liberty', denomination='Dollar', year=1838, confidence='high', notes='Confirmed via dealer listing (SKU 141915): "1838 s1 j 84 restrike pr65".'),
    dict(file='141917fs.jpg', series='Morgan', denomination='Dollar', year=1892, confidence='high', notes='Confirmed via dealer listing (SKU 141917): "1892 s morgan s1 ms63", mint mark S.'),
    dict(file='142157fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1849, confidence='medium', notes=''),
    dict(file='142265fs.jpg', series='Draped Bust', denomination='Dime', year=1801, confidence='high', notes='Confirmed via dealer listing (SKU 142265): "1801 draped bust 10c ms64 plus".'),
    dict(file='142267fs.jpg', series='Draped Bust', denomination='Half Dollar', year=1803, confidence='high', notes='Confirmed via dealer listing (SKU 142267): "1803 draped bust 50c small 3 ms62 plus".'),
    dict(file='142268fs.jpg', series='Seated Liberty', denomination='Dime (likely)', year=1885, confidence='low', notes='Date partially legible.'),
    dict(file='142269fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1914, confidence='medium', notes=''),
    dict(file='142270fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1900, confidence='medium', notes=''),
    dict(file='142271fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1847, confidence='medium', notes=''),
    dict(file='142283fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1834, confidence='medium', notes='Date partially legible.'),
    dict(file='142333fs.jpg', series='Seated Liberty', denomination='Dollar', year=1839, confidence='high', notes='Confirmed via dealer listing (SKU 142333): "1839 gobrecht s1 j 104res restrike pr64 plus".'),
    dict(file='142343fs.jpg', series='Seated Liberty (full legend, Arrows?)', denomination='uncertain (dime)', year=1871, confidence='low', notes='"UNITED STATES OF AMERICA" legend obverse variant; denomination/date uncertain.'),
    dict(file='142344fs.jpg', series='Seated Liberty (Arrows)', denomination='Quarter (likely)', year=1854, confidence='medium', notes=''),
    dict(file='142397fs.jpg', series='uncertain bust type', denomination='uncertain', year=1859, confidence='low', notes='Hairstyle resembles Draped Bust but 1859 postdates that series - date or design may be misread, needs verification.'),
    dict(file='142460fs.jpg', series='Continental Currency', denomination='Dollar (pewter/brass)', year=1776, confidence='high', notes='Confirmed via dealer listing (SKU 142460): "1776 eg fecit pewter 1 ms65".'),
    dict(file='142473fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1870, confidence='medium', notes=''),
    dict(file='142495fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1861, confidence='medium', notes=''),
    dict(file='142496fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half/dollar)', year=1870, confidence='medium', notes=''),
    dict(file='142497fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half/dollar)', year=1873, confidence='medium', notes=''),
    dict(file='142513fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1871, confidence='medium', notes=''),
    dict(file='142539fs.jpg', series='Seated Liberty (full legend)', denomination='Dime (likely)', year=1860, confidence='medium', notes=''),
    dict(file='142542fs.jpg', series='Capped Bust', denomination='Quarter', year=1821, confidence='high', notes='Confirmed via dealer listing (SKU 142542): "1821 capped bust 25c ms65".'),
    dict(file='142543fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1856, confidence='low', notes='Date partially legible.'),
    dict(file='142545fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1844, confidence='medium', notes=''),
    dict(file='142553fs.jpg', series='Barber (full legend)', denomination='uncertain (dime/quarter/half)', year=1892, confidence='high', notes='1892 is the first year of the Barber design.'),
    dict(file='142586fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1824, confidence='high', notes=''),
    dict(file='142587fs.jpg', series='Liberty Seated', denomination='Dollar', year=1857, confidence='high', notes='Confirmed via dealer listing (SKU 142587): "1857 liberty seated s1 no motto pr65".'),
    dict(file='142608fs.jpg', series='Indian Princess Head Gold', denomination='uncertain ($1 or $2.50 gold)', year=1875, confidence='high', notes='Confirmed via dealer listing (SKU 142608): "1875 indian princess 3 pr65 deep cameo".'),
    dict(file='142636fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1858, confidence='medium', notes=''),
    dict(file='142640fs.jpg', series='Peace', denomination='Dollar', year=1934, confidence='high', notes='Confirmed via dealer listing (SKU 142640): "1934 d peace 1 ms66 plus", mint mark D.'),
    dict(file='142745fs.jpg', series='Continental', denomination='Dollar (pewter/brass)', year=1776, confidence='high', notes='Confirmed via dealer listing (SKU 142745): "1776 continental 1 curency pewter ms63".'),
    dict(file='142761fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=None, confidence='low', notes='Date not legible.'),
    dict(file='142763fs.jpg', series='Draped Bust', denomination='Quarter', year=1806, confidence='high', notes='Confirmed via dealer listing (SKU 142763): "1806 draped bust 25c heraldic eagle ms65".'),
    dict(file='142932fs.jpg', series='Capped Bust', denomination='Quarter', year=1832, confidence='high', notes='Confirmed via dealer listing (SKU 142932): "1832 capped bust 25c ms65".'),
    dict(file='142991fs.jpg', series='Mercury (Winged Liberty Head)', denomination='Dime', year=None, confidence='low', notes="Date reads oddly like 1912, which predates the design's 1916 debut - likely misread (possibly 1942); needs verification."),
    dict(file='142994fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1859, confidence='medium', notes=''),
    dict(file='142995fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1857, confidence='medium', notes=''),
    dict(file='142997fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1904, confidence='low', notes='Date partially legible.'),
    dict(file='142998fs.jpg', series='Walking Liberty', denomination='Half Dollar', year=None, confidence='medium', notes='Date not legible in this crop.'),
    dict(file='142999fs.jpg', series='Draped Bust', denomination='Dollar', year=1798, confidence='high', notes=''),
    dict(file='143023fs.jpg', series='Draped Bust', denomination='Half Dollar', year=1806, confidence='high', notes='Confirmed via dealer listing (SKU 143023): "1806 draped bust 50c pointed 6 no stem ms64".'),
    dict(file='143030fs.jpg', series='Draped Bust', denomination='Dime', year=1805, confidence='high', notes='Confirmed via dealer listing (SKU 143030): "1805 draped bust 10c 4 berries ms66".'),
    dict(file='143031fs.jpg', series='Liberty Seated', denomination='Dollar', year=1866, confidence='high', notes='Confirmed via dealer listing (SKU 143031): "1866 liberty seated s1 motto pr66 plus deep cameo".'),
    dict(file='143044fs.jpg', series='Draped Bust', denomination='Dollar', year=1798, confidence='high', notes=''),
    dict(file='143045fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1831, confidence='high', notes=''),
    dict(file='143055fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half/dollar)', year=1871, confidence='medium', notes=''),
    dict(file='143097fs.jpg', series='Morgan', denomination='Dollar', year=1884, confidence='high', notes='Confirmed via dealer listing (SKU 143097): "1884 s morgan s1 ms63", mint mark S.'),
    dict(file='143111fs.jpg', series='Draped Bust', denomination='Dime', year=1804, confidence='high', notes='Confirmed via dealer listing (SKU 143111): "1804 draped bust 10c 13 stars reverse au53".'),
    dict(file='143113fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1849, confidence='medium', notes=''),
    dict(file='143114fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1846, confidence='medium', notes=''),
    dict(file='143123fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1812, confidence='low', notes='Date partially legible.'),
    dict(file='143146fs.jpg', series='Capped Bust (reduced diameter)', denomination='Dime', year=1828, confidence='medium', notes=''),
    dict(file='143148fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1898, confidence='medium', notes=''),
    dict(file='143149fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1829, confidence='high', notes=''),
    dict(file='143150fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1838, confidence='high', notes=''),
    dict(file='143156fs.jpg', series='Seated Liberty (full legend)', denomination='uncertain (quarter/half)', year=1854, confidence='medium', notes=''),
    dict(file='143175fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1844, confidence='medium', notes=''),
    dict(file='143184fs.jpg', series='Morgan', denomination='Dollar', year=1882, confidence='high', notes='Confirmed via dealer listing (SKU 143184): "1882 morgan s1 ms67".'),
    dict(file='143195fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1817, confidence='high', notes=''),
    dict(file='143242fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1909, confidence='medium', notes=''),
    dict(file='143288fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1861, confidence='medium', notes=''),
    dict(file='143332fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1859, confidence='medium', notes=''),
    dict(file='143334fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1865, confidence='medium', notes=''),
    dict(file='143378fs.jpg', series='Mercury (Winged Liberty Head)', denomination='Dime', year=1942, confidence='high', notes=''),
    dict(file='143388fs.jpg', series='Morgan', denomination='Dollar', year=1897, confidence='high', notes='Confirmed via dealer listing (SKU 143388): "1897 morgan s1 ms66 dmpl".'),
    dict(file='143399fs.jpg', series='Seated Liberty (full legend)', denomination='Dollar', year=1864, confidence='medium', notes=''),
    dict(file='143404fs.jpg', series='Trade Dollar', denomination='Dollar', year=1873, confidence='high', notes='First year of the Trade Dollar series.'),
    dict(file='143408fs.jpg', series='Trade Dollar', denomination='Dollar', year=1875, confidence='medium', notes=''),
    dict(file='143413fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1899, confidence='medium', notes=''),
    dict(file='143486fs.jpg', series='Continental', denomination='Dollar (pewter/brass)', year=1776, confidence='high', notes='Confirmed via dealer listing (SKU 143486): "1776 continental 1 pewter \'eg fecit\' ms64".'),
    dict(file='143489fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1855, confidence='medium', notes=''),
    dict(file='143490fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1815, confidence='high', notes=''),
    dict(file='143508fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half/dime)', year=1882, confidence='medium', notes=''),
    dict(file='143545fs.jpg', series='Shield', denomination='Nickel (5 cents)', year=1867, confidence='high', notes='Confirmed via dealer listing (SKU 143545): "1867 shield 5c rays pr65".'),
    dict(file='143547fs.jpg', series='Morgan', denomination='Dollar', year=1890, confidence='high', notes='Confirmed via dealer listing (SKU 143547): "1890 cc morgan s1 tailbar ms65 plus", mint mark CC.'),
    dict(file='143550fs.jpg', series='Walking Liberty', denomination='Half Dollar', year=None, confidence='low', notes='Date partially legible, likely late 1910s.'),
    dict(file='143580fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1809, confidence='high', notes='Confirmed via dealer listing (SKU 143580): "1809 capped bust 50c ms65 plus".'),
    dict(file='143581fs.jpg', series='Trade Dollar', denomination='Dollar', year=1875, confidence='medium', notes=''),
    dict(file='143599fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half/dollar)', year=1859, confidence='medium', notes=''),
    dict(file='143710fs.jpg', series='Continental', denomination='Dollar (pewter/brass)', year=1776, confidence='high', notes='Confirmed via dealer listing (SKU 143710): "1776 continental 1 curency pewter ms63".'),
    dict(file='143735fs.jpg', series='Walking Liberty', denomination='Half Dollar', year=1916, confidence='high', notes='First year of the design.'),
    dict(file='143741fs.jpg', series='Flowing Hair', denomination='Half Dollar', year=1794, confidence='high', notes='Confirmed via dealer listing (SKU 143741): "1794 flowing hair 50c au50".'),
    dict(file='143742fs.jpg', series='Capped Bust', denomination='Quarter', year=1820, confidence='high', notes='Confirmed via dealer listing (SKU 143742): "1820 capped bust 25c small 0 ms66 plus".'),
    dict(file='143743fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1895, confidence='low', notes='Date partially legible.'),
    dict(file='143789fs.jpg', series='Liberty Seated', denomination='Dollar', year=1841, confidence='high', notes='Confirmed via dealer listing (SKU 143789): "1841 liberty seated s1 no motto ms64".'),
    dict(file='143798fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half/dollar)', year=1852, confidence='low', notes='Date partially legible.'),
    dict(file='143799fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1846, confidence='medium', notes=''),
    dict(file='143801fs.jpg', series='Liberty Seated', denomination='Dollar', year=1842, confidence='high', notes='Confirmed via dealer listing (SKU 143801): "1842 liberty seated s1 no motto ms64 plus".'),
    dict(file='143802fs.jpg', series='Liberty Seated', denomination='Dollar', year=1844, confidence='high', notes='Confirmed via dealer listing (SKU 143802): "1844 liberty seated s1 no motto ms64".'),
    dict(file='143803fs.jpg', series='Liberty Seated', denomination='Dollar', year=1844, confidence='high', notes='Confirmed via dealer listing (SKU 143803): "1844 liberty seated s1 no motto pr65".'),
    dict(file='143804fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1849, confidence='medium', notes=''),
    dict(file='143832fs.jpg', series='Walking Liberty', denomination='Half Dollar', year=1941, confidence='high', notes=''),
    dict(file='143839fs.jpg', series='Panama-Pacific Commemorative Gold (octagonal)', denomination='$50 Gold', year=1852, confidence='high', notes='Confirmed via dealer listing (SKU 143839): "1852 887 assay 50 au58".'),
    dict(file='143851fs.jpg', series='Seated Liberty', denomination='Dollar', year=1854, confidence='high', notes=''),
    dict(file='143868fs.jpg', series='Washington', denomination='Quarter', year=None, confidence='low', notes="Reads oddly like 1916, which predates the design's 1932 debut - likely misread (possibly 1936); needs verification."),
    dict(file='143916fs.jpg', series='Seated Liberty', denomination='Dollar', year=1863, confidence='high', notes=''),
    dict(file='143919fs.jpg', series='Morgan', denomination='Dollar', year=1886, confidence='high', notes='Confirmed via dealer listing (SKU 143919): "1886 o morgan s1 ms65", mint mark O.'),
    dict(file='143927fs.jpg', series='Draped Bust', denomination='uncertain', year=1802, confidence='high', notes='Confirmed via dealer listing (SKU 143927): "1802 draped bust h10c au50".'),
    dict(file='143928fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1854, confidence='medium', notes=''),
    dict(file='143929fs.jpg', series='Seated Liberty (Arrows)', denomination='uncertain (quarter/half)', year=1874, confidence='medium', notes=''),
    dict(file='143930fs.jpg', series='Seated Liberty', denomination='Dollar', year=1847, confidence='high', notes=''),
    dict(file='143945fs.jpg', series='Liberty Head (Coronet)', denomination='$20 Gold (Double Eagle, likely)', year=1861, confidence='high', notes='Confirmed via dealer listing (SKU 143945): "1861 s liberty head 20 paquet xf45", mint mark S.'),
    dict(file='143963fs.jpg', series='Walking Liberty', denomination='Half Dollar', year=1921, confidence='high', notes='1921 is a key date for this series.'),
    dict(file='143975fs.jpg', series='Peace', denomination='Dollar', year=1926, confidence='high', notes='Confirmed via dealer listing (SKU 143975): "1926 s peace 1 ms66 plus", mint mark S.'),
    dict(file='143989fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1813, confidence='high', notes=''),
    dict(file='144000fs.jpg', series='Peace', denomination='Dollar', year=1925, confidence='high', notes='Confirmed via dealer listing (SKU 144000): "1925 s peace 1 ms65", mint mark S.'),
    dict(file='144010fs.jpg', series='Flowing Hair', denomination='Half Dollar', year=1794, confidence='high', notes='Confirmed via dealer listing (SKU 144010): "1794 flowing hair 50c au55".'),
    dict(file='144011fs.jpg', series='Walking Liberty', denomination='Half Dollar', year=1936, confidence='high', notes=''),
    dict(file='144012fs.jpg', series='Seated Liberty', denomination='Dollar', year=1847, confidence='high', notes=''),
    dict(file='144013fs.jpg', series='Liberty Seated', denomination='Dollar', year=1852, confidence='high', notes='Confirmed via dealer listing (SKU 144013): "1852 liberty seated s1 restrike pr63".'),
    dict(file='144024fs.jpg', series='Seated Liberty (full legend)', denomination='Dime', year=1867, confidence='medium', notes=''),
    dict(file='144029fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1870, confidence='medium', notes=''),
    dict(file='144041fs.jpg', series='Seated Liberty (full legend)', denomination='Dime', year=1878, confidence='medium', notes=''),
    dict(file='144245fs.jpg', series='Morgan', denomination='Dollar', year=1879, confidence='high', notes='Confirmed via dealer listing (SKU 144245): "1879 cc morgan s1 capped die ms65", mint mark CC.'),
    dict(file='144266fs.jpg', series='Morgan', denomination='Dollar', year=1897, confidence='high', notes='Confirmed via dealer listing (SKU 144266): "1897 morgan s1 ms66 dmpl".'),
    dict(file='144321fs.jpg', series='Seated Liberty (Arrows)', denomination='uncertain (quarter/half)', year=1874, confidence='medium', notes=''),
    dict(file='144394fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1855, confidence='medium', notes=''),
    dict(file='144395fs.jpg', series='Seated Liberty', denomination='Dollar', year=1870, confidence='low', notes='Date partially legible.'),
    dict(file='144398fs.jpg', series='Seated Liberty (full legend)', denomination='Dime', year=1860, confidence='medium', notes=''),
    dict(file='144400fs.jpg', series='Morgan', denomination='Dollar', year=1882, confidence='high', notes='Confirmed via dealer listing (SKU 144400): "1882 os morgan s1 os strong ms65".'),
    dict(file='144423fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1868, confidence='medium', notes=''),
    dict(file='144426fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1861, confidence='medium', notes=''),
    dict(file='144427fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1847, confidence='medium', notes=''),
    dict(file='144432fs.jpg', series='Capped Bust', denomination='uncertain (half/dime)', year=None, confidence='low', notes='Date reads oddly like 1840, which is late for this design - likely misread (possibly 1830/1834).'),
    dict(file='144474fs.jpg', series='Mercury (Winged Liberty Head)', denomination='Dime', year=1942, confidence='high', notes=''),
    dict(file='144475fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=None, confidence='low', notes='Date obscured by dark background lighting.'),
    dict(file='144489fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1900, confidence='medium', notes=''),
    dict(file='144493fs.jpg', series='Draped Bust', denomination='Dime', year=1804, confidence='high', notes='Confirmed via dealer listing (SKU 144493): "1804 draped bust 10c 14 stars reverse au53".'),
    dict(file='144495fs.jpg', series='Capped Bust', denomination='Quarter', year=1836, confidence='high', notes='Confirmed via dealer listing (SKU 144495): "1836 capped bust 25c ms65".'),
    dict(file='144496fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1873, confidence='medium', notes=''),
    dict(file='144497fs.jpg', series='Flowing Hair', denomination='Half Dollar', year=1794, confidence='high', notes='Confirmed via dealer listing (SKU 144497): "1794 flowing hair 50c au58".'),
    dict(file='144498fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1834, confidence='high', notes=''),
    dict(file='144499fs.jpg', series='Seated Liberty (Arrows)', denomination='uncertain (quarter/half)', year=1873, confidence='medium', notes=''),
    dict(file='144512fs.jpg', series='Liberty Seated', denomination='Dollar', year=1864, confidence='high', notes='Confirmed via dealer listing (SKU 144512): "1864 liberty seated s1 no motto ms65".'),
    dict(file='144520fs.jpg', series='Morgan', denomination='Dollar', year=1885, confidence='high', notes='Confirmed via dealer listing (SKU 144520): "1885 cc morgan s1 ms67 plus", mint mark CC.'),
    dict(file='144528fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1811, confidence='high', notes='Confirmed via dealer listing (SKU 144528): "1811 capped bust 50c small 8 ms66 plus".'),
    dict(file='144534fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1860, confidence='medium', notes=''),
    dict(file='144558fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1909, confidence='medium', notes=''),
    dict(file='144565fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=None, confidence='low', notes='Date not legible.'),
    dict(file='144574fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1880, confidence='medium', notes=''),
    dict(file='144579fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1846, confidence='medium', notes=''),
    dict(file='144593fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1902, confidence='medium', notes=''),
    dict(file='144594fs.jpg', series='Barber', denomination='Half Dollar (likely)', year=1909, confidence='medium', notes=''),
    dict(file='144599fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1897, confidence='low', notes='Date partially legible.'),
    dict(file='144600fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1860, confidence='medium', notes='Watermarked "Imaged by Heritage Auctions" - confirms these fs.jpg photos are auction-house reference images.'),
    dict(file='144618fs.jpg', series='Draped Bust', denomination='Dollar', year=1795, confidence='high', notes=''),
    dict(file='144619fs.jpg', series='Seated Liberty (full legend)', denomination='Dime', year=1863, confidence='medium', notes=''),
    dict(file='144622fs.jpg', series='Capped Bust', denomination='Quarter', year=1828, confidence='high', notes='Confirmed via dealer listing (SKU 144622): "1828 capped bust 25c pr65".'),
    dict(file='144623fs.jpg', series='Liberty Seated', denomination='Quarter', year=1842, confidence='high', notes='Confirmed via dealer listing (SKU 144623): "1842 o liberty seated 25c small date ms62 plus", mint mark O.'),
    dict(file='144624fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1870, confidence='medium', notes=''),
    dict(file='144626fs.jpg', series='Draped Bust', denomination='Half Dollar', year=1797, confidence='high', notes='Confirmed via dealer listing (SKU 144626): "1797 draped bust 50c ms55 plus".'),
    dict(file='144631fs.jpg', series='Draped Bust', denomination='Dollar', year=1798, confidence='low', notes='Date partially legible.'),
    dict(file='144632fs.jpg', series='Capped Bust (reduced diameter)', denomination='Dime', year=1834, confidence='medium', notes=''),
    dict(file='144638fs.jpg', series='Walking Liberty', denomination='Half Dollar', year=1921, confidence='high', notes='Key date for this series.'),
    dict(file='144647fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1848, confidence='medium', notes=''),
    dict(file='144651fs.jpg', series='Liberty Seated', denomination='Dollar', year=1868, confidence='high', notes='Confirmed via dealer listing (SKU 144651): "1868 liberty seated s1 motto pr66 plus deep cameo".'),
    dict(file='144656fs.jpg', series='Walking Liberty', denomination='Half Dollar', year=1916, confidence='high', notes='First year of the design.'),
    dict(file='144657fs.jpg', series='Seated Liberty', denomination='Half Dime (likely)', year=1836, confidence='low', notes='Date/denomination uncertain, small-size seated design.'),
    dict(file='144663fs.jpg', series='Draped Bust', denomination='Dime', year=1797, confidence='high', notes='Confirmed via dealer listing (SKU 144663): "1797 draped bust 10c 13 stars ms62 plus".'),
    dict(file='144665fs.jpg', series='Seated Liberty', denomination='Dollar', year=1872, confidence='high', notes=''),
    dict(file='144666fs.jpg', series='Liberty Seated', denomination='Dollar', year=1847, confidence='high', notes='Confirmed via dealer listing (SKU 144666): "1847 liberty seated s1 no motto pr64".'),
    dict(file='144667fs.jpg', series='Liberty Seated', denomination='Dollar', year=1849, confidence='high', notes='Confirmed via dealer listing (SKU 144667): "1849 liberty seated s1 no motto pr65".'),
    dict(file='144680fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1850, confidence='medium', notes=''),
    dict(file='144682fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1859, confidence='medium', notes=''),
    dict(file='144690fs.jpg', series='Seated Liberty (full legend)', denomination='Dollar', year=1874, confidence='high', notes=''),
    dict(file='144696fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1836, confidence='high', notes='Confirmed via dealer listing (SKU 144696): "1836 capped bust 50c 5000 lettered edge ms64 plus".'),
    dict(file='144714fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1891, confidence='high', notes='Final year of the Seated Liberty quarter/half series.'),
    dict(file='144716fs.jpg', series='Trade Dollar', denomination='Dollar', year=1874, confidence='low', notes='Date partially legible.'),
    dict(file='144722fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1850, confidence='low', notes='Date partially legible.'),
    dict(file='144723fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1904, confidence='medium', notes=''),
    dict(file='144726fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1899, confidence='medium', notes=''),
    dict(file='144740fs.jpg', series='Liberty Seated', denomination='Dollar', year=1842, confidence='high', notes='Confirmed via dealer listing (SKU 144740): "1842 liberty seated s1 no motto pr65".'),
    dict(file='144743fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1839, confidence='high', notes='Confirmed via dealer listing (SKU 144743): "1839 gobrecht 1 j 104 res pr65".'),
    dict(file='144750fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1860, confidence='medium', notes=''),
    dict(file='144755fs.jpg', series='Liberty Seated', denomination='Quarter', year=1840, confidence='high', notes='Confirmed via dealer listing (SKU 144755): "1840 liberty seated 25c drapery ms64 plus".'),
    dict(file='144756fs.jpg', series='Liberty Seated', denomination='Quarter', year=1842, confidence='high', notes='Confirmed via dealer listing (SKU 144756): "1842 o liberty seated 25c small date ms61", mint mark O.'),
    dict(file='144757fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1852, confidence='medium', notes=''),
    dict(file='144762fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1856, confidence='low', notes='Date partially legible.'),
    dict(file='144764fs.jpg', series='Seated Liberty', denomination='Dollar', year=1870, confidence='high', notes=''),
    dict(file='144766fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1878, confidence='medium', notes=''),
    dict(file='144767fs.jpg', series='Seated Liberty', denomination='Dime (likely)', year=1888, confidence='medium', notes=''),
    dict(file='144768fs.jpg', series='Standing Liberty', denomination='Quarter', year=1917, confidence='medium', notes='Covered-breast (Type 2) style suggests 1917-1930 range.'),
    dict(file='144770fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1847, confidence='medium', notes=''),
    dict(file='144771fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1855, confidence='medium', notes=''),
    dict(file='144774fs.jpg', series='Seated Liberty (Arrows)', denomination='uncertain (quarter/half)', year=1873, confidence='medium', notes=''),
    dict(file='144776fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half/dollar)', year=1878, confidence='medium', notes=''),
    dict(file='144784fs.jpg', series='Panama-Pacific Commemorative Gold (octagonal)', denomination='$50 Gold', year=1852, confidence='high', notes='Confirmed via dealer listing (SKU 144784): "1852 887 assay 50 au58".'),
    dict(file='144785fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1870, confidence='medium', notes=''),
    dict(file='144870fs.jpg', series='Seated Liberty (Arrows)', denomination='uncertain (quarter/half)', year=1873, confidence='medium', notes=''),
    dict(file='144871fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1807, confidence='high', notes='Confirmed via dealer listing (SKU 144871): "1807 capped bust 50c large stars 5020 ms64 plus".'),
    dict(file='144872fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1907, confidence='medium', notes=''),
    dict(file='144891fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1854, confidence='medium', notes=''),
    dict(file='144894fs.jpg', series='Draped Bust', denomination='Dime', year=1796, confidence='high', notes='Confirmed via dealer listing (SKU 144894): "1796 draped bust 10c small eagle ms66".'),
    dict(file='144896fs.jpg', series='Capped Bust', denomination='uncertain', year=1808, confidence='high', notes='Confirmed via dealer listing (SKU 144896): "1808 capped bust 25 au55".'),
    dict(file='144903fs.jpg', series='Seated Liberty', denomination='Dollar', year=1838, confidence='high', notes='Confirmed via dealer listing (SKU 144903): "1838 s1 j 84 restrike pr65".'),
    dict(file='144911fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1857, confidence='medium', notes=''),
    dict(file='144921fs.jpg', series='Morgan', denomination='Dollar', year=1897, confidence='high', notes='Confirmed via dealer listing (SKU 144921): "1897 o morgan s1 ms65", mint mark O.'),
    dict(file='144925fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1858, confidence='medium', notes=''),
    dict(file='144941fs.jpg', series='Seated Liberty', denomination='Dollar', year=1836, confidence='high', notes='Confirmed via dealer listing (SKU 144941): "1836 gobrecht s1 pr64".'),
    dict(file='144960fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=None, confidence='low', notes='Date obscured by toning.'),
    dict(file='144964fs.jpg', series='Liberty Seated', denomination='Dollar', year=1844, confidence='high', notes='Confirmed via dealer listing (SKU 144964): "1844 liberty seated s1 no motto pr65".'),
    dict(file='144965fs.jpg', series='Morgan', denomination='Dollar', year=1886, confidence='high', notes='Confirmed via dealer listing (SKU 144965): "1886 o morgan s1 ms65", mint mark O.'),
    dict(file='144976fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1858, confidence='medium', notes=''),
    dict(file='144983fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1856, confidence='medium', notes=''),
    dict(file='145028fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1846, confidence='medium', notes=''),
    dict(file='145051fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1868, confidence='medium', notes=''),
    dict(file='145053fs.jpg', series='Draped Bust', denomination='Half Dollar', year=1802, confidence='high', notes='Confirmed via dealer listing (SKU 145053): "1802 draped bust 50c ms62".'),
    dict(file='145071fs.jpg', series='Liberty Seated', denomination='Quarter', year=1840, confidence='high', notes='Confirmed via dealer listing (SKU 145071): "1840 liberty seated 25c drapery pr64".'),
    dict(file='145072fs.jpg', series='Liberty Seated', denomination='Quarter', year=1841, confidence='high', notes='Confirmed via dealer listing (SKU 145072): "1841 liberty seated 25c pr61".'),
    dict(file='145073fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=None, confidence='low', notes='Date not legible.'),
    dict(file='145075fs.jpg', series='Washington', denomination='Quarter', year=None, confidence='low', notes='Silver-era toning suggests pre-1965; exact date not legible.'),
    dict(file='145076fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1842, confidence='medium', notes=''),
    dict(file='145077fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1849, confidence='medium', notes=''),
    dict(file='145078fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1852, confidence='medium', notes=''),
    dict(file='145083fs.jpg', series='Seated Liberty', denomination='Dollar', year=1836, confidence='high', notes='Confirmed via dealer listing (SKU 145083): "1836 gobrecht s1 j 60 original   coin alignment pr65".'),
    dict(file='145084fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1843, confidence='medium', notes=''),
    dict(file='145085fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1848, confidence='medium', notes=''),
    dict(file='145122fs.jpg', series='Capped Bust', denomination='uncertain (half/dime)', year=1837, confidence='low', notes='Photographed inside a certification slab.'),
    dict(file='145123fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1857, confidence='medium', notes=''),
    dict(file='145127fs.jpg', series='Standing Liberty', denomination='Quarter', year=1918, confidence='low', notes='Date partially legible.'),
    dict(file='145131fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1851, confidence='medium', notes=''),
    dict(file='145132fs.jpg', series='Morgan', denomination='Dollar', year=1889, confidence='high', notes='Confirmed via dealer listing (SKU 145132): "1889 cc morgan s1 ms64 plus", mint mark CC.'),
    dict(file='145139fs.jpg', series='Liberty Head Gold (Coronet)', denomination='$2.50 Quarter Eagle', year=1841, confidence='medium', notes='1841 quarter eagles are a famous major rarity ("Little Princess") if genuine business-strike/proof - likely a museum reference photo, not a coin in hand.'),
    dict(file='145188fs.jpg', series='Continental', denomination='Dollar (pewter/brass)', year=1776, confidence='high', notes='Confirmed via dealer listing (SKU 145188): "1776 continental currency 1 curency pewter ms62".'),
    dict(file='145207fs.jpg', series='Draped Bust', denomination='Dollar', year=1795, confidence='high', notes=''),
    dict(file='145208fs.jpg', series='Seated Liberty', denomination='Dollar', year=1863, confidence='high', notes=''),
    dict(file='145211fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1855, confidence='medium', notes=''),
    dict(file='145232fs.jpg', series='Liberty Head Gold (Coronet)', denomination='$20 Double Eagle', year=1861, confidence='high', notes='Confirmed via dealer listing (SKU 145232): "1861 s liberty head 20 paquet au53", mint mark S.'),
    dict(file='145244fs.jpg', series='Walking Liberty', denomination='Half Dollar', year=None, confidence='low', notes='Photographed inside an NGC slab; date not legible in this crop.'),
    dict(file='145255fs.jpg', series='Mercury (Winged Liberty Head)', denomination='Dime', year=1942, confidence='low', notes='Date partially legible.'),
    dict(file='145256fs.jpg', series='Draped Bust', denomination='Quarter', year=1806, confidence='high', notes='Confirmed via dealer listing (SKU 145256): "1806 draped bust 25c heraldic eagle ms64".'),
    dict(file='145261fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1812, confidence='high', notes=''),
    dict(file='145262fs.jpg', series='Draped Bust', denomination='Dollar', year=1798, confidence='high', notes=''),
    dict(file='145269fs.jpg', series='Draped Bust', denomination='Dollar', year=1799, confidence='low', notes='Date partially legible.'),
    dict(file='145282fs.jpg', series='Draped Bust', denomination='Dollar', year=1797, confidence='high', notes='Confirmed via dealer listing (SKU 145282): "1797 draped bust 1 9x7 large letters au58".'),
    dict(file='145287fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1834, confidence='low', notes='Date partially legible.'),
    dict(file='145313fs.jpg', series='Walking Liberty', denomination='Half Dollar', year=1918, confidence='low', notes='Date partially legible.'),
    dict(file='145316fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1858, confidence='medium', notes=''),
    dict(file='145328fs.jpg', series='Washington', denomination='Quarter', year=None, confidence='low', notes='Silver-era toning suggests 1930s; exact date not legible.'),
    dict(file='145336fs.jpg', series='Panama-Pacific Commemorative Gold (round)', denomination='$50 Gold', year=1915, confidence='high', notes='Confirmed via dealer listing (SKU 145336): "1915 s gold 50 pan pac round ms65", mint mark S.'),
    dict(file='145349fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1840, confidence='medium', notes=''),
    dict(file='145351fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1865, confidence='medium', notes=''),
    dict(file='145441fs.jpg', series='Walking Liberty', denomination='Half Dollar', year=1921, confidence='high', notes='Key date for this series.'),
    dict(file='145504fs.jpg', series='Capped Bust', denomination='Half Dollar', year=1814, confidence='low', notes='Date partially legible.'),
    dict(file='145508fs.jpg', series='Draped Bust', denomination='Dollar', year=1795, confidence='high', notes=''),
    dict(file='145509fs.jpg', series='Morgan', denomination='Dollar', year=1879, confidence='high', notes='Confirmed via dealer listing (SKU 145509): "1879 cc morgan s1 capped die ms65", mint mark CC.'),
    dict(file='145511fs.jpg', series='Flowing Hair', denomination='fractional gold token', year=1879, confidence='high', notes='Confirmed via dealer listing (SKU 145511): "1879 4 stella flowing hair pr67 plus".'),
    dict(file='145532fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=None, confidence='low', notes='Date not legible, worn.'),
    dict(file='145554fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1913, confidence='medium', notes=''),
    dict(file='145563fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1856, confidence='low', notes='Date partially legible.'),
    dict(file='145565fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1840, confidence='medium', notes=''),
    dict(file='145568fs.jpg', series='Seated Liberty (full legend)', denomination='Dollar (likely)', year=1865, confidence='low', notes='Dark-field proof-like photo.'),
    dict(file='145570fs.jpg', series='Flowing Hair', denomination='fractional gold token', year=1879, confidence='high', notes='Confirmed via dealer listing (SKU 145570): "1879 4 stella flowing hair pr65".'),
    dict(file='145571fs.jpg', series='Capped Bust', denomination='Dime', year=1820, confidence='high', notes='Confirmed via dealer listing (SKU 145571): "1820 capped bust 10c small 0 ms67".'),
    dict(file='145572fs.jpg', series='Flowing Hair', denomination='Half Dollar', year=1795, confidence='high', notes='Confirmed via dealer listing (SKU 145572): "1795 flowing hair 50c ms63".'),
    dict(file='145576fs.jpg', series='Seated Liberty', denomination='Dollar', year=1851, confidence='low', notes='Date partially legible.'),
    dict(file='145578fs.jpg', series='Draped Bust', denomination='Dollar', year=1806, confidence='low', notes='Date partially legible.'),
    dict(file='145579fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half/dollar)', year=None, confidence='low', notes='Worn, date not legible.'),
    dict(file='145586fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1861, confidence='medium', notes=''),
    dict(file='145590fs.jpg', series='Barber', denomination='uncertain (quarter/half)', year=1903, confidence='medium', notes=''),
    dict(file='145593fs.jpg', series='Walking Liberty', denomination='Half Dollar', year=1936, confidence='low', notes='Date partially legible.'),
    dict(file='145594fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1872, confidence='medium', notes=''),
    dict(file='145596fs.jpg', series='Seated Liberty', denomination='Dollar', year=1841, confidence='low', notes='Photographed inside an NGC slab; date partially legible.'),
    dict(file='145600fs.jpg', series='Seated Liberty (Arrows and Rays)', denomination='Quarter', year=1853, confidence='medium', notes=''),
    dict(file='145601fs.jpg', series='Standing Liberty', denomination='Quarter', year=1923, confidence='high', notes=''),
    dict(file='145604fs.jpg', series='Seated Liberty', denomination='uncertain (quarter/half)', year=1848, confidence='medium', notes=''),
    dict(file='145606fs.jpg', series='Walking Liberty', denomination='Half Dollar', year=1936, confidence='high', notes=''),
]
